<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="XSD">
      <schema location="../xsd/PaymentData.xsd"/>
      <rootElement name="Input" namespace="http://PaymentData"/>
      <param name="PaymentDataDetails" />
    </source>
  </mapSources>
  <mapTargets>
    <target type="XSD">
      <schema location="../xsd/GetLookUpsFrmDB.xsd"/>
      <rootElement name="GetLookUpsFrmDBInput" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/GetLookUpsFrmDB"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 150407.0554.0203) AT [SUN DEC 27 00:32:57 GST 2015]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/GetLookUpsFrmDB"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:pymnt="http://PaymentData"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:bpmn="http://schemas.oracle.com/bpm/xpath"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl pymnt xsd ns0 bpws xp20 mhdr bpel oraext dvm hwf med ids bpm xdk xref bpmn ora socket ldap">
  <xsl:template match="/">
    <ns0:GetLookUpsFrmDBInput>
      <ns0:ownernationality>
        <xsl:value-of select="/pymnt:Input/pymnt:UserDetails/pymnt:nationality"/>
      </ns0:ownernationality>
      <ns0:usrnationality>
        <xsl:value-of select="/pymnt:Input/pymnt:UserDetails/pymnt:nationality"/>
      </ns0:usrnationality>
      <ns0:emirate_id>
        <xsl:value-of select="/pymnt:Input/pymnt:UserDetails/pymnt:Emirate"/>
      </ns0:emirate_id>
      <ns0:typeofuserid1>
        <xsl:value-of select="/pymnt:Input/pymnt:UserDetails/pymnt:TypeOfUser"/>
      </ns0:typeofuserid1>
      <ns0:typeofuserid2>
        <xsl:value-of select="/pymnt:Input/pymnt:UserDetails/pymnt:TypeOfUser"/>
      </ns0:typeofuserid2>
      <ns0:sourcetype1>
        <xsl:text disable-output-escaping="no">2</xsl:text>
      </ns0:sourcetype1>
      <ns0:sourcetype2>
        <xsl:text disable-output-escaping="no">2</xsl:text>
      </ns0:sourcetype2>
      <ns0:apptype1>
        <xsl:value-of select="/pymnt:Input/pymnt:UserDetails/pymnt:applicanttypeid"/>
      </ns0:apptype1>
      <ns0:apptype2>
        <xsl:value-of select="/pymnt:Input/pymnt:UserDetails/pymnt:applicanttypeid"/>
      </ns0:apptype2>
    </ns0:GetLookUpsFrmDBInput>
  </xsl:template>
</xsl:stylesheet>
