<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="XSD">
      <schema location="../xsd/PaymentData.xsd"/>
      <rootElement name="Input" namespace="http://PaymentData"/>
      <param name="PaymentDataDetails" />
    </source>
    <source type="XSD">
      <schema location="../xsd/Cashier_Payment_Details_Service_table.xsd"/>
      <rootElement name="CashierPaymentDetailsCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/Cashier_Payment_Details_Service"/>
      <param name="cashierPaymentDetailsCollectionOutput" />
    </source>
  </mapSources>
  <mapTargets>
    <target type="XSD">
      <schema location="../xsd/PaymentData.xsd"/>
      <rootElement name="Input" namespace="http://PaymentData"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.8(build 150622.2350.0222) AT [SUN JAN 24 16:16:25 GST 2016]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/top/Cashier_Payment_Details_Service"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:pymnt="http://PaymentData"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:bpmn="http://schemas.oracle.com/bpm/xpath"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl ns0 pymnt xsd bpws xp20 mhdr bpel oraext dvm hwf med ids bpm xdk xref bpmn ora socket ldap">
  <xsl:param name="cashierPaymentDetailsCollectionOutput"/>
  <xsl:template match="/">
    <pymnt:Input>
      <pymnt:UserDetails>
        <pymnt:Username>
          <xsl:value-of select="/pymnt:Input/pymnt:UserDetails/pymnt:Username"/>
        </pymnt:Username>
        <pymnt:TypeOfUser>
          <xsl:value-of select="/pymnt:Input/pymnt:UserDetails/pymnt:TypeOfUser"/>
        </pymnt:TypeOfUser>
        <pymnt:Accountid>
          <xsl:value-of select="/pymnt:Input/pymnt:UserDetails/pymnt:Accountid"/>
        </pymnt:Accountid>
        <pymnt:MobileNo>
          <xsl:value-of select="/pymnt:Input/pymnt:UserDetails/pymnt:MobileNo"/>
        </pymnt:MobileNo>
        <pymnt:EmailID>
          <xsl:value-of select="/pymnt:Input/pymnt:UserDetails/pymnt:EmailID"/>
        </pymnt:EmailID>
        <pymnt:EmiratesId>
          <xsl:value-of select="/pymnt:Input/pymnt:UserDetails/pymnt:EmiratesId"/>
        </pymnt:EmiratesId>
        <pymnt:TradeLienceNo>
          <xsl:value-of select="/pymnt:Input/pymnt:UserDetails/pymnt:TradeLienceNo"/>
        </pymnt:TradeLienceNo>
        <pymnt:FamilyBookNo>
          <xsl:value-of select="/pymnt:Input/pymnt:UserDetails/pymnt:FamilyBookNo"/>
        </pymnt:FamilyBookNo>
        <pymnt:nationality>
          <xsl:value-of select="/pymnt:Input/pymnt:UserDetails/pymnt:nationality"/>
        </pymnt:nationality>
        <pymnt:Emirate>
          <xsl:value-of select="/pymnt:Input/pymnt:UserDetails/pymnt:Emirate"/>
        </pymnt:Emirate>
        <pymnt:FirstName>
          <xsl:value-of select="/pymnt:Input/pymnt:UserDetails/pymnt:FirstName"/>
        </pymnt:FirstName>
        <pymnt:MiddleName>
          <xsl:value-of select="/pymnt:Input/pymnt:UserDetails/pymnt:MiddleName"/>
        </pymnt:MiddleName>
        <pymnt:LastName>
          <xsl:value-of select="/pymnt:Input/pymnt:UserDetails/pymnt:LastName"/>
        </pymnt:LastName>
        <pymnt:Address1>
          <xsl:value-of select="/pymnt:Input/pymnt:UserDetails/pymnt:Address1"/>
        </pymnt:Address1>
        <pymnt:Address2>
          <xsl:value-of select="/pymnt:Input/pymnt:UserDetails/pymnt:Address2"/>
        </pymnt:Address2>
        <pymnt:Address3>
          <xsl:value-of select="/pymnt:Input/pymnt:UserDetails/pymnt:Address3"/>
        </pymnt:Address3>
        <pymnt:POBOX>
          <xsl:value-of select="/pymnt:Input/pymnt:UserDetails/pymnt:POBOX"/>
        </pymnt:POBOX>
        <pymnt:DOB>
          <xsl:value-of select="/pymnt:Input/pymnt:UserDetails/pymnt:DOB"/>
        </pymnt:DOB>
        <pymnt:applicanttypeid>
          <xsl:value-of select="/pymnt:Input/pymnt:UserDetails/pymnt:applicanttypeid"/>
        </pymnt:applicanttypeid>
        <pymnt:applicanttype_en>
          <xsl:value-of select="/pymnt:Input/pymnt:UserDetails/pymnt:applicanttype_en"/>
        </pymnt:applicanttype_en>
        <pymnt:applicanttype_ar>
          <xsl:value-of select="/pymnt:Input/pymnt:UserDetails/pymnt:applicanttype_ar"/>
        </pymnt:applicanttype_ar>
        <pymnt:nationality_en>
          <xsl:value-of select="/pymnt:Input/pymnt:UserDetails/pymnt:nationality_en"/>
        </pymnt:nationality_en>
        <pymnt:nationality_ar>
          <xsl:value-of select="/pymnt:Input/pymnt:UserDetails/pymnt:nationality_ar"/>
        </pymnt:nationality_ar>
        <pymnt:emirate_en>
          <xsl:value-of select="/pymnt:Input/pymnt:UserDetails/pymnt:emirate_en"/>
        </pymnt:emirate_en>
        <pymnt:emirate_ar>
          <xsl:value-of select="/pymnt:Input/pymnt:UserDetails/pymnt:emirate_ar"/>
        </pymnt:emirate_ar>
        <pymnt:typeofuser_en>
          <xsl:value-of select="/pymnt:Input/pymnt:UserDetails/pymnt:typeofuser_en"/>
        </pymnt:typeofuser_en>
        <pymnt:typeofuser_ar>
          <xsl:value-of select="/pymnt:Input/pymnt:UserDetails/pymnt:typeofuser_ar"/>
        </pymnt:typeofuser_ar>
      </pymnt:UserDetails>
      <pymnt:RequestDetails>
        <pymnt:ServiceId>
          <xsl:value-of select="/pymnt:Input/pymnt:RequestDetails/pymnt:ServiceId"/>
        </pymnt:ServiceId>
        <pymnt:ServiceName>
          <xsl:value-of select="/pymnt:Input/pymnt:RequestDetails/pymnt:ServiceName"/>
        </pymnt:ServiceName>
        <pymnt:RequestType>
          <xsl:value-of select="/pymnt:Input/pymnt:RequestDetails/pymnt:RequestType"/>
        </pymnt:RequestType>
        <pymnt:RequestDate>
          <xsl:value-of select="/pymnt:Input/pymnt:RequestDetails/pymnt:RequestDate"/>
        </pymnt:RequestDate>
        <pymnt:FeeTypeCode>
          <xsl:value-of select="/pymnt:Input/pymnt:RequestDetails/pymnt:FeeTypeCode"/>
        </pymnt:FeeTypeCode>
        <pymnt:UserType>
          <xsl:value-of select="/pymnt:Input/pymnt:RequestDetails/pymnt:UserType"/>
        </pymnt:UserType>
        <pymnt:Letter>
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/pymnt:Input/pymnt:RequestDetails/pymnt:Letter/@xsi:nil"/>
          </xsl:attribute>
          <xsl:value-of select="/pymnt:Input/pymnt:RequestDetails/pymnt:Letter"/>
        </pymnt:Letter>
        <pymnt:RequestNumber>
          <xsl:value-of select="/pymnt:Input/pymnt:RequestDetails/pymnt:RequestNumber"/>
        </pymnt:RequestNumber>
        <pymnt:RequestStatus>
          <xsl:value-of select="/pymnt:Input/pymnt:RequestDetails/pymnt:RequestStatus"/>
        </pymnt:RequestStatus>
        <pymnt:cashierGrpName>
          <xsl:value-of select="/pymnt:Input/pymnt:RequestDetails/pymnt:cashierGrpName"/>
        </pymnt:cashierGrpName>
      </pymnt:RequestDetails>
      <pymnt:PaymentDetails>
        <pymnt:TotalAmount>
          <xsl:value-of select="/pymnt:Input/pymnt:PaymentDetails/pymnt:TotalAmount"/>
        </pymnt:TotalAmount>
        <pymnt:GeneralAmount>
          <xsl:value-of select="/pymnt:Input/pymnt:PaymentDetails/pymnt:GeneralAmount"/>
        </pymnt:GeneralAmount>
        <pymnt:ApplicationAmount>
          <xsl:value-of select="/pymnt:Input/pymnt:PaymentDetails/pymnt:ApplicationAmount"/>
        </pymnt:ApplicationAmount>
        <pymnt:ServiceAmount>
          <xsl:value-of select="/pymnt:Input/pymnt:PaymentDetails/pymnt:ServiceAmount"/>
        </pymnt:ServiceAmount>
        <pymnt:specificDeptCode>
          <xsl:value-of select="/pymnt:Input/pymnt:PaymentDetails/pymnt:specificDeptCode"/>
        </pymnt:specificDeptCode>
        <pymnt:GeneralDeptCode>
          <xsl:value-of select="/pymnt:Input/pymnt:PaymentDetails/pymnt:GeneralDeptCode"/>
        </pymnt:GeneralDeptCode>
        <pymnt:SpecificFeeId>
          <xsl:value-of select="/pymnt:Input/pymnt:PaymentDetails/pymnt:SpecificFeeId"/>
        </pymnt:SpecificFeeId>
        <pymnt:GeneralFeeId>
          <xsl:value-of select="/pymnt:Input/pymnt:PaymentDetails/pymnt:GeneralFeeId"/>
        </pymnt:GeneralFeeId>
        <pymnt:PaymentMethod>
          <xsl:value-of select="/pymnt:Input/pymnt:PaymentDetails/pymnt:PaymentMethod"/>
        </pymnt:PaymentMethod>
        <pymnt:DepartmentName>
          <xsl:value-of select="/pymnt:Input/pymnt:PaymentDetails/pymnt:DepartmentName"/>
        </pymnt:DepartmentName>
      </pymnt:PaymentDetails>
      <pymnt:POSDetails>
        <pymnt:Amount>
          <xsl:value-of select="/pymnt:Input/pymnt:POSDetails/pymnt:Amount"/>
        </pymnt:Amount>
        <pymnt:EcrIdNo>
          <xsl:value-of select="$cashierPaymentDetailsCollectionOutput/ns0:CashierPaymentDetailsCollection/ns0:CashierPaymentDetails/ns0:id"/>
        </pymnt:EcrIdNo>
        <pymnt:ServiceCode>
          <xsl:value-of select="/pymnt:Input/pymnt:POSDetails/pymnt:ServiceCode"/>
        </pymnt:ServiceCode>
        <pymnt:TransactionType>
          <xsl:value-of select="/pymnt:Input/pymnt:POSDetails/pymnt:TransactionType"/>
        </pymnt:TransactionType>
        <pymnt:TerminalNo>
          <xsl:value-of select="/pymnt:Input/pymnt:POSDetails/pymnt:TerminalNo"/>
        </pymnt:TerminalNo>
        <pymnt:MerchantId>
          <xsl:value-of select="/pymnt:Input/pymnt:POSDetails/pymnt:MerchantId"/>
        </pymnt:MerchantId>
        <pymnt:PaymentId>
          <xsl:value-of select="/pymnt:Input/pymnt:POSDetails/pymnt:PaymentId"/>
        </pymnt:PaymentId>
        <pymnt:FeeId>
          <xsl:value-of select="/pymnt:Input/pymnt:POSDetails/pymnt:FeeId"/>
        </pymnt:FeeId>
        <pymnt:CustomerId>
          <xsl:value-of select="/pymnt:Input/pymnt:POSDetails/pymnt:CustomerId"/>
        </pymnt:CustomerId>
        <pymnt:CustomerName>
          <xsl:value-of select="/pymnt:Input/pymnt:POSDetails/pymnt:CustomerName"/>
        </pymnt:CustomerName>
      </pymnt:POSDetails>
      <pymnt:AccountIdentityAttachmentList>
        <xsl:for-each select="/pymnt:Input/pymnt:AccountIdentityAttachmentList/pymnt:accountAttachmentRec">
          <pymnt:accountAttachmentRec>
            <pymnt:contentid>
              <xsl:value-of select="pymnt:contentid"/>
            </pymnt:contentid>
            <pymnt:doctypeid>
              <xsl:value-of select="pymnt:doctypeid"/>
            </pymnt:doctypeid>
            <pymnt:doctype_en>
              <xsl:value-of select="pymnt:doctype_en"/>
            </pymnt:doctype_en>
            <pymnt:doctype_ar>
              <xsl:value-of select="pymnt:doctype_ar"/>
            </pymnt:doctype_ar>
            <pymnt:viewurl>
              <xsl:value-of select="pymnt:viewurl"/>
            </pymnt:viewurl>
            <pymnt:downloadurl>
              <xsl:value-of select="pymnt:downloadurl"/>
            </pymnt:downloadurl>
            <pymnt:filename>
              <xsl:value-of select="pymnt:filename"/>
            </pymnt:filename>
          </pymnt:accountAttachmentRec>
        </xsl:for-each>
      </pymnt:AccountIdentityAttachmentList>
    </pymnt:Input>
  </xsl:template>
</xsl:stylesheet>
