package ae.payment.model.client;

import ae.payment.model.common.UaqAppModule;

import ae.payment.model.pojo.PaymentRequestECR;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Feb 09 16:02:26 EET 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class UaqAppModuleClient extends ApplicationModuleImpl implements UaqAppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public UaqAppModuleClient() {
    }


    public Number getSequenceNumber(String sequenceName) {
        Object _ret =
            this.riInvokeExportedMethod(this,"getSequenceNumber",new String [] {"java.lang.String"},new Object[] {sequenceName});
        return (Number)_ret;
    }

    public PaymentRequestECR getBrokenTransactionOnParticularPOS(String merchantId,
                                                                 String terminalNo) {
        Object _ret =
            this.riInvokeExportedMethod(this,"getBrokenTransactionOnParticularPOS",new String [] {"java.lang.String","java.lang.String"},new Object[] {merchantId, terminalNo});
        return (PaymentRequestECR)_ret;
    }

    public String getSequenceByDepartment(String sequenceName) {
        Object _ret =
            this.riInvokeExportedMethod(this,"getSequenceByDepartment",new String [] {"java.lang.String"},new Object[] {sequenceName});
        return (String)_ret;
    }

    public PaymentRequestECR getPaymentInProgressOnAnotherPOS(String paymentId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"getPaymentInProgressOnAnotherPOS",new String [] {"java.lang.String"},new Object[] {paymentId});
        return (PaymentRequestECR)_ret;
    }
}
