package ae.payment.model.common;

import ae.payment.model.pojo.PaymentRequestECR;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Feb 09 16:02:26 EET 2016
// ---------------------------------------------------------------------
public interface UaqAppModule extends ApplicationModule {
    Number getSequenceNumber(String sequenceName);


    PaymentRequestECR getBrokenTransactionOnParticularPOS(String merchantId,
                                                          String terminalNo);

    String getSequenceByDepartment(String sequenceName);

    PaymentRequestECR getPaymentInProgressOnAnotherPOS(String paymentId);
}
