package com.uaq.ws.util;

import java.util.Hashtable;

public class PublicDataUtils {
	public static String getSex(String sex)
	{
		if("M".equals(sex))
			return "Male";
		else if("F".equals(sex))
			return "Female";
		else
        if("X".equals(sex))    
			return "Unknown";
        
        return "";
	}
	
	public static String getOccupation(String occupation)
	{
		if(occupation == null)
			return "";
		return (String)occupations.get(""+Integer.parseInt(occupation));
	}
	
	public static String getMaritalStatus(String maritalStatus)
	{
		if(maritalStatus == null)
			return "";
		String[] maritalStatuses = new String[]{"--", "Single", "Married", "Divorced", "Widowed"};
        
		return maritalStatuses[Integer.parseInt(maritalStatus)];
	}
	
	public static String getSponsorType(String sponsorType)
	{
		if(sponsorType == null)
			return "";
		String[] SponsorTypes = new String[]{"Parent", "Spoose", "", "", "Sheikh", "UAE Citizen", "Resident", "GCC Sponsor", "Diplomatic", "Company", "Federal Government", "Local Government", "Assimilated Government", "Heritance", "", "", "", "", "Other Sponsor type"};
		
		return SponsorTypes[Integer.parseInt(sponsorType)+3];
	}
	
	public static String getResidencyType(String residencyType)
	{
		if(residencyType == null)
			return "";
		String[] ResidencyTypes = new String[]{"", "", "Work", "Resident", "Diplomatic", "", "", "Service"};
		
		return ResidencyTypes[Integer.parseInt(residencyType)];
	}
	
	public static String removeCommas(String source) {
		if(",,".equals(source))
			return "";
		else if(source == null)
			return "";
		return source.replace(",", " ").replace("  ", " ");
	}
	
	private static final Hashtable occupations = new Hashtable();
	
	static {
		occupations.put(String.valueOf(0), "Armed forces");
		occupations.put(String.valueOf(1), "Legislators, senior officials and managers");
		occupations.put(String.valueOf(2), "Professionals");     
		occupations.put(String.valueOf(3), "Technicians and associate professionals"); 
		occupations.put(String.valueOf(4), "Clerks");     
		occupations.put(String.valueOf(5), "Service workers and shop and market sales workers");        
		occupations.put(String.valueOf(6), "Skilled agricultural and fishery workers");      
		occupations.put(String.valueOf(7), "Craft and related trades workers");    
		occupations.put(String.valueOf(8), "Plant and machine operators and assemblers");      
		occupations.put(String.valueOf(9), "Elementary occupations"); 
		occupations.put(String.valueOf(10), "House Wife"); 
		occupations.put(String.valueOf(11), "Student");
		occupations.put(String.valueOf(96), "Unknown occupation");  
		occupations.put(String.valueOf(97) ,"Retired");
		occupations.put(String.valueOf(98), "-"); 
		occupations.put(String.valueOf(99), "Unemployed"); 
		occupations.put(String.valueOf(1110), "Legislators"); 
		occupations.put(String.valueOf(1120), "Senior government officials");        
		occupations.put(String.valueOf(1130), "Traditional chiefs and heads of villages");    
		occupations.put(String.valueOf(1141), "Senior officials of political-party organizations");      
		occupations.put(String.valueOf(1142), "Senior officials of employers, workers and other economic-interest organizations");        
		occupations.put(String.valueOf(1143), "Senior officials of humanitarian and other special-interest organisations");        
		occupations.put(String.valueOf(1210), "Directors and chief executives");       
		occupations.put(String.valueOf(1221), "Production and operations department managers (agr., hunting, forestry & fish.)");         
		occupations.put(String.valueOf(1222), "Production and operations department managers in manufacturing");       
		occupations.put(String.valueOf(1223), "Production and operations department managers in construction");       
		occupations.put(String.valueOf(1224), "Production and operations department managers in wholesale and retail trade");        
		occupations.put(String.valueOf(1225), "Production and operations department managers in restaurants and hotels");       
		occupations.put(String.valueOf(1226), "Production & operations department managers (transport, storage & communication)");        
		occupations.put(String.valueOf(1227), "Production and operations department managers in business services");      
		occupations.put(String.valueOf(1228), "Production & operations department managers (personal care, cleaning & services)");         
		occupations.put(String.valueOf(1229), "Production and operations department managers not elsewhere classified");         
		occupations.put(String.valueOf(1231), "Finance and administration department managers");   
		occupations.put(String.valueOf(1232), "Personnel and industrial relations department managers");   
		occupations.put(String.valueOf(1233), "Sales and marketing department managers");   
		occupations.put(String.valueOf(1234), "Advertising and public relations department managers");    
		occupations.put(String.valueOf(1235), "Supply and distribution department managers");   
		occupations.put(String.valueOf(1236), "Computing services department managers");   
		occupations.put(String.valueOf(1237), "Research and development department managers");   
		occupations.put(String.valueOf(1238), "Statistics, Economics & Planning Department Managers");    
		occupations.put(String.valueOf(1239), "Other department managers not elsewhere classified");  
		occupations.put(String.valueOf(1311), "General managers in agriculture, hunting, forestry/ and fishing");       
		occupations.put(String.valueOf(1312), "General managers in manufacturing");   
		occupations.put(String.valueOf(1313), "General managers in construction");   
		occupations.put(String.valueOf(1314), "General managers in wholesale and retail trade");     
		occupations.put(String.valueOf(1315), "General managers of restaurants and hotels");    
		occupations.put(String.valueOf(1316), "General managers in transport, storage and communications");     
		occupations.put(String.valueOf(1317), "General managers of business services");    
		occupations.put(String.valueOf(1318), "General managers in personal care, cleaning and related services");       
		occupations.put(String.valueOf(1319), "General managers not elsewhere classified");   
		occupations.put(String.valueOf(2111), "Physicists and astronomers");   
		occupations.put(String.valueOf(2112), "Meteorologists");    
		occupations.put(String.valueOf(2113), "Chemists"); 
		occupations.put(String.valueOf(2114), "Geologists and geophysicists");
		occupations.put(String.valueOf(2121), "Mathematicians and related professionals");     
		occupations.put(String.valueOf(2122), "Statisticians"); 
		occupations.put(String.valueOf(2131), "Computer systems designers and analysts");     
		occupations.put(String.valueOf(2132), "Computer programmers");  
		occupations.put(String.valueOf(2139), "Computing professionals not elsewhere classified");    
		occupations.put(String.valueOf(2141), "Architects, town and traffic planners");      
		occupations.put(String.valueOf(2142), "Civil engineers");  
		occupations.put(String.valueOf(2143), "Electrical engineers");  
		occupations.put(String.valueOf(2144), "Electronics and telecommunications engineers");   
		occupations.put(String.valueOf(2145), "Mechanical engineers");  
		occupations.put(String.valueOf(2146), "Chemical engineers");  
		occupations.put(String.valueOf(2147), "Mining engineers, metallurgists and related professionals");
		occupations.put(String.valueOf(2148), "Cartographers and surveyors");    
		occupations.put(String.valueOf(2149), "Architects, engineers and related professionals not elsewhere classified");          
		occupations.put(String.valueOf(2211), "Biologists, botanists, zoologists and related professionals");        
		occupations.put(String.valueOf(2212), "Pharmacologists, pathologists and related professionals");       
		occupations.put(String.valueOf(2213), "Agronomists and related professionals");  
		occupations.put(String.valueOf(2221), "Medical doctors");  
		occupations.put(String.valueOf(2222), "Dentists");  
		occupations.put(String.valueOf(2223), "Veterinarians");  
		occupations.put(String.valueOf(2224), "Pharmacists"); 
		occupations.put(String.valueOf(2229), "Health professionals (except nursing) not elsewhere classified");            
		occupations.put(String.valueOf(2230), "Nursing and midwifery professionals");      
		occupations.put(String.valueOf(2310), "College, university and higher education teaching professionals");  
		occupations.put(String.valueOf(2320), "Secondary education teaching professionals");   
		occupations.put(String.valueOf(2331), "Primary education teaching professionals");     
		occupations.put(String.valueOf(2332), "Pre-primary education teaching professionals");    
		occupations.put(String.valueOf(2340), "Special education teaching professionals");    
		occupations.put(String.valueOf(2351), "Education methods specialists");   
		occupations.put(String.valueOf(2352), "School inspectors");  
		occupations.put(String.valueOf(2353), "Other teaching professionals not elsewhere classified");    
		occupations.put(String.valueOf(2411), "Accountants"); 
		occupations.put(String.valueOf(2412), "Personnel and careers professionals");    
		occupations.put(String.valueOf(2413), "Business professionals not elsewhere classified");    
		occupations.put(String.valueOf(2421), "Lawyers"); 
		occupations.put(String.valueOf(2422), "Judges"); 
		occupations.put(String.valueOf(2423), "Legal professionals not elsewhere classified");         
		occupations.put(String.valueOf(2431), "Archivists and curators");   
		occupations.put(String.valueOf(2432), "Librarians and related information professionals");  
		occupations.put(String.valueOf(2441), "Economists"); 
		occupations.put(String.valueOf(2442), "Sociologists, anthropologists and related professionals");      
		occupations.put(String.valueOf(2443), "Philosophers, historians and political scientists");      
		occupations.put(String.valueOf(2444), "Philologists, translators and interpreters"); 
		occupations.put(String.valueOf(2445), "Psychologists");    
		occupations.put(String.valueOf(2446), "Social work professionals");    
		occupations.put(String.valueOf(2451), "Authors, journalists and other writers");  
		occupations.put(String.valueOf(2452), "Sculptors, painters and related artists");
		occupations.put(String.valueOf(2453), "Composers, musicians and singers");    
		occupations.put(String.valueOf(2454), "Choreographers and dancers");   
		occupations.put(String.valueOf(2455), "Film, stage and related actors and directors");  
		occupations.put(String.valueOf(2460), "Religious professionals");  
		occupations.put(String.valueOf(3111), "Chemical and physical science technicians");  
		occupations.put(String.valueOf(3112), "Civil engineering technicians");   
		occupations.put(String.valueOf(3113), "Electrical engineering technicians");   
		occupations.put(String.valueOf(3114), "Electronics and telecommunications engineering technicians");     
		occupations.put(String.valueOf(3115), "Mechanical engineering technicians");   
		occupations.put(String.valueOf(3116), "Chemical engineering technicians");   
		occupations.put(String.valueOf(3117), "Mining and metallurgical technicians");     
		occupations.put(String.valueOf(3118), "Draughtspersons");  
		occupations.put(String.valueOf(3119), "Physical and engineering science technicians not elsewhere classified");      
		occupations.put(String.valueOf(3121), "Computer assistants");  
		occupations.put(String.valueOf(3122), "Computer equipment operators");  
		occupations.put(String.valueOf(3123), "Industrial robot controllers");      
		occupations.put(String.valueOf(3131), "Photographers and image and sound recording equipment operators"); 
		occupations.put(String.valueOf(3132), "Broadcasting and telecommunications equipment operators");      
		occupations.put(String.valueOf(3133), "Medical equipment operators");
		occupations.put(String.valueOf(3139), "Optical and electronic equipment operators not elsewhere classified");     
		occupations.put(String.valueOf(3141), "Ships' engineers");     
		occupations.put(String.valueOf(3142), "Ships' deck officers and pilots");   
		occupations.put(String.valueOf(3143), "Aircraft pilots and related associate professionals");  
		occupations.put(String.valueOf(3144), "Air traffic controllers");       
		occupations.put(String.valueOf(3145), "Air traffic safety technicians");    
		occupations.put(String.valueOf(3151), "Building and fire inspectors");   
		occupations.put(String.valueOf(3152), "Safety, health and quality inspectors");     
		occupations.put(String.valueOf(3211), "Life science technicians");   
		occupations.put(String.valueOf(3212), "Agronomy and forestry technicians");     
		occupations.put(String.valueOf(3213), "Farming and forestry advisers");  
		occupations.put(String.valueOf(3221), "Medical assistants");   
		occupations.put(String.valueOf(3222), "Sanitarians");    
		occupations.put(String.valueOf(3223), "Dieticians and nutritionists");  
		occupations.put(String.valueOf(3224), "Optometrists and opticians");   
		occupations.put(String.valueOf(3225), "Dental assistants");   
		occupations.put(String.valueOf(3226), "Physiotherapists and related associate professionals");   
		occupations.put(String.valueOf(3227), "Veterinary assistants");   
		occupations.put(String.valueOf(3228), "Pharmaceutical assistants");  
		occupations.put(String.valueOf(3229), "Modern health associate professionals (except nursing) not elsewhere classified");      
		occupations.put(String.valueOf(3231), "Nursing associate professionals");    
		occupations.put(String.valueOf(3232), "Midwifery associate professionals");    
		occupations.put(String.valueOf(3241), "Traditional medicine practitioners");   
		occupations.put(String.valueOf(3242), "Faith healers");      
		occupations.put(String.valueOf(3310), "Primary education teaching associate professionals");      
		occupations.put(String.valueOf(3320), "Pre-primary education teaching associate professionals");      
		occupations.put(String.valueOf(3330), "Special education teaching associate professionals");      
		occupations.put(String.valueOf(3340), "Other teaching associate professionals");   
		occupations.put(String.valueOf(3411), "Securities and finance dealers and brokers"); 
		occupations.put(String.valueOf(3412), "Insurance representatives");  
		occupations.put(String.valueOf(3413), "Estate agents");  
		occupations.put(String.valueOf(3414), "Travel consultants and organisers");   
		occupations.put(String.valueOf(3415), "Technical and commercial sales representatives");  
		occupations.put(String.valueOf(3416), "Buyers");  
		occupations.put(String.valueOf(3417), "Appraisers, valuers and auctioneers");  
		occupations.put(String.valueOf(3419), "Finance and sales associate professionals not elsewhere classified");        
		occupations.put(String.valueOf(3421), "Trade brokers");  
		occupations.put(String.valueOf(3422), "Clearing and forwarding agents");    
		occupations.put(String.valueOf(3423), "Employment agents and labour contractors");  
		occupations.put(String.valueOf(3424), "Business services agents and trade brokers not elsewhere classified");      
		occupations.put(String.valueOf(3431), "Administrative secretaries and related associate professionals");  
		occupations.put(String.valueOf(3432), "Legal and related business associate professionals"); 
		occupations.put(String.valueOf(3433), "Bookkeepers");
		occupations.put(String.valueOf(3434), "Statistical, mathematical and related associate professionals");     
		occupations.put(String.valueOf(3435), "Administrative associate professionals not elsewhere classified");  
		occupations.put(String.valueOf(3441), "Customs and border inspectors");     
		occupations.put(String.valueOf(3442), "Government tax and excise officials");   
		occupations.put(String.valueOf(3443), "Government social benefits officials");     
		occupations.put(String.valueOf(3444), "Government licensing officials");    
		occupations.put(String.valueOf(3445), "Police inspectors and detectives");   
		occupations.put(String.valueOf(3449), "Customs, tax and related government associate professionals");        
		occupations.put(String.valueOf(3451), "Social work associate professionals");      
		occupations.put(String.valueOf(3461), "Decorators and commercial designers");   
		occupations.put(String.valueOf(3462), "Radio, television and other announcers");     
		occupations.put(String.valueOf(3463), "Street, night-club and related musicians, singers and dancers");         
		occupations.put(String.valueOf(3464), "Clowns, magicians, acrobats and related associate professionals");     
		occupations.put(String.valueOf(3465), "Athletes, sportspersons and related associate professionals");     
		occupations.put(String.valueOf(3470), "Religious associate professionals"); 
		occupations.put(String.valueOf(4111), "Stenographers and typists"); 
		occupations.put(String.valueOf(4112), "Word-processor and related operators");      
		occupations.put(String.valueOf(4113), "Data entry operators");    
		occupations.put(String.valueOf(4114), "Calculating-machine operators");   
		occupations.put(String.valueOf(4115), "Secretaries"); 
		occupations.put(String.valueOf(4121), "Accounting and bookkeeping clerks");  
		occupations.put(String.valueOf(4122), "Statistical and finance clerks");  
		occupations.put(String.valueOf(4131), "Stock clerks");   
		occupations.put(String.valueOf(4132), "Production clerks");   
		occupations.put(String.valueOf(4133), "Transport clerks");   
		occupations.put(String.valueOf(4141), "Library and filing clerks");   
		occupations.put(String.valueOf(4142), "Mail carriers and sorting clerks");     
		occupations.put(String.valueOf(4143), "Coding, proof-reading and related clerks");    
		occupations.put(String.valueOf(4144), "Scribes and related workers"); 
		occupations.put(String.valueOf(4190), "Other office clerks");   
		occupations.put(String.valueOf(4211), "Cashiers and ticket clerks");     
		occupations.put(String.valueOf(4212), "Tellers and other counter clerks");      
		occupations.put(String.valueOf(4213), "Bookmakers and croupiers");     
		occupations.put(String.valueOf(4214), "Pawnbrokers and money-lenders");       
		occupations.put(String.valueOf(4215), "Debt-collectors and related workers");     
		occupations.put(String.valueOf(4221), "Travel agency and related clerks");    
		occupations.put(String.valueOf(4222), "Receptionists and information clerks");   
		occupations.put(String.valueOf(4223), "Telephone switchboard operators");  
		occupations.put(String.valueOf(5111), "Travel attendants and travel stewards");    
		occupations.put(String.valueOf(5112), "Transport conductors");       
		occupations.put(String.valueOf(5113), "Travel guides");      
		occupations.put(String.valueOf(5121), "Housekeepers and related workers");
		occupations.put(String.valueOf(5122), "Cooks"); 
		occupations.put(String.valueOf(5123), "Waiters, waitresses and bartenders");   
		occupations.put(String.valueOf(5131), "Child-care workers"); 
		occupations.put(String.valueOf(5132), "Institution-based personal care workers");      
		occupations.put(String.valueOf(5133), "Home-based personal care workers");     
		occupations.put(String.valueOf(5134), "Personal care and related workers not elsewhere classified");     
		occupations.put(String.valueOf(5141), "Hairdressers, barbers, beauticians and related workers");     
		occupations.put(String.valueOf(5142), "Companions and valets");  
		occupations.put(String.valueOf(5143), "Undertakers and embalmers");     
		occupations.put(String.valueOf(5144), "Other personal services workers not elsewhere classified");    
		occupations.put(String.valueOf(5151), "Astrologers and related workers");   
		occupations.put(String.valueOf(5152), "Fortune-tellers, palmists and related workers");      
		occupations.put(String.valueOf(5161), "Fire-fighters");    
		occupations.put(String.valueOf(5162), "Police officers"); 
		occupations.put(String.valueOf(5163), "Prison guards");  
		occupations.put(String.valueOf(5164), "Protective services workers not elsewhere classified");    
		occupations.put(String.valueOf(5210), "Fashion and other models");    
		occupations.put(String.valueOf(5220), "Shop salespersons and demonstrators");   
		occupations.put(String.valueOf(5230), "Stall and market salespersons");   
		occupations.put(String.valueOf(6111), "Field crop and vegetable growers");   
		occupations.put(String.valueOf(6112), "Tree and shrub crop growers");   
		occupations.put(String.valueOf(6113), "Gardeners, horticultural and nursery growers");   
		occupations.put(String.valueOf(6114), "Mixed-crop growers");   
		occupations.put(String.valueOf(6121), "Dairy and livestock producers");   
		occupations.put(String.valueOf(6122), "Poultry producers");  
		occupations.put(String.valueOf(6123), "Apiarists and sericulturists");    
		occupations.put(String.valueOf(6124), "Mixed-animal producers");   
		occupations.put(String.valueOf(6129), "Market-oriented animal producers and related workers not elsewhere classified");      
		occupations.put(String.valueOf(6130), "Market-oriented crop and animal producers");      
		occupations.put(String.valueOf(6141), "Forestry workers and loggers");     
		occupations.put(String.valueOf(6142), "Charcoal burners and related workers");     
		occupations.put(String.valueOf(6151), "Aquatic-life cultivation workers");    
		occupations.put(String.valueOf(6152), "Inland and coastal waters fishery workers");     
		occupations.put(String.valueOf(6153), "Deep-sea fishery workers");      
		occupations.put(String.valueOf(6154), "Hunters and trappers");   
		occupations.put(String.valueOf(6210), "Subsistence agricultural and fishery workers");        
		occupations.put(String.valueOf(7111), "Miners and quarry workers");    
		occupations.put(String.valueOf(7112), "Shotfirers and blasters");     
		occupations.put(String.valueOf(7113), "Stone splitters, cutters and carvers");  
		occupations.put(String.valueOf(7121), "Builders, traditional materials");   
		occupations.put(String.valueOf(7122), "Bricklayers and stonemasons");    
		occupations.put(String.valueOf(7123), "Concrete placers, concrete finishers and related workers");   
		occupations.put(String.valueOf(7124), "Carpenters and joiners");   
		occupations.put(String.valueOf(7125), "Building frame and related trades workers not elsewhere classified");    
		occupations.put(String.valueOf(7131), "Roofers");    
		occupations.put(String.valueOf(7132), "Floor layers and tile setters"); 
		occupations.put(String.valueOf(7133), "Plasterers");    
		occupations.put(String.valueOf(7134), "Insulation workers");   
		occupations.put(String.valueOf(7135), "Glaziers"); 
		occupations.put(String.valueOf(7136), "Building and related electricians");     
		occupations.put(String.valueOf(7137), "Plumbers and pipe fitters");   
		occupations.put(String.valueOf(7141), "Painters and related workers");    
		occupations.put(String.valueOf(7142), "Varnishers and related painters");     
		occupations.put(String.valueOf(7143), "Tiles & Wooden Plats fitters");      
		occupations.put(String.valueOf(7144), "Building structure cleaners");   
		occupations.put(String.valueOf(7211), "Metal moulders and coremakers");      
		occupations.put(String.valueOf(7212), "Welders and flamecutters");    
		occupations.put(String.valueOf(7213), "Sheet metal workers");    
		occupations.put(String.valueOf(7214), "Structural-metal preparers and erectors");     
		occupations.put(String.valueOf(7215), "Riggers and cable splicers");     
		occupations.put(String.valueOf(7216), "Underwater workers");    
		occupations.put(String.valueOf(7221), "Blacksmiths, hammer-smiths and forging-press workers");    
		occupations.put(String.valueOf(7222), "Tool-makers and related workers");     
		occupations.put(String.valueOf(7223), "Machine-tool setters and setter-operators");      
		occupations.put(String.valueOf(7224), "Metal wheel-grinders, polishers and tool sharpeners");        
		occupations.put(String.valueOf(7231), "Motor vehicle mechanics and fitters");  
		occupations.put(String.valueOf(7232), "Aircraft engine mechanics and fitters");     
		occupations.put(String.valueOf(7239), "Agricultural- or industrial-machinery mechanics and fitters");    
		occupations.put(String.valueOf(7241), "Electrical mechanics and fitters");        
		occupations.put(String.valueOf(7242), "Electronics fitters");       
		occupations.put(String.valueOf(7243), "Electronics mechanics and servicers");    
		occupations.put(String.valueOf(7244), "Telegraph and telephone installers and servicers");     
		occupations.put(String.valueOf(7245), "Electrical line installers, repairers and cable jointers");      
		occupations.put(String.valueOf(7311), "Precision-instrument makers and repairers");    
		occupations.put(String.valueOf(7312), "Musical instrument makers and tuners");    
		occupations.put(String.valueOf(7313), "Jewellery and precious-metal workers");    
		occupations.put(String.valueOf(7321), "Abrasive wheel formers, potters and related workers");     
		occupations.put(String.valueOf(7322), "Glass makers, cutters, grinders and finishers");      
		occupations.put(String.valueOf(7323), "Glass engravers and etchers");    
		occupations.put(String.valueOf(7324), "Glass, ceramics and related decorative painters");     
		occupations.put(String.valueOf(7331), "Handicraft workers in wood and related materials");       
		occupations.put(String.valueOf(7332), "Handicraft workers in textile, leather and related materials");       
		occupations.put(String.valueOf(7341), "Compositors, typesetters and related workers");     
		occupations.put(String.valueOf(7342), "Stereotypers and electrotypers");    
		occupations.put(String.valueOf(7343), "Printing engravers and etchers");   
		occupations.put(String.valueOf(7344), "Photographic and related workers");   
		occupations.put(String.valueOf(7345), "Bookbinders and related workers");     
		occupations.put(String.valueOf(7346), "Silk-screen, block and textile printers");    
		occupations.put(String.valueOf(7411), "Butchers, fishmongers and related food preparers");     
		occupations.put(String.valueOf(7412), "Bakers, pastry-cooks and confectionery makers");    
		occupations.put(String.valueOf(7413), "Dairy-products makers");    
		occupations.put(String.valueOf(7414), "Fruit, vegetable and related preservers");    
		occupations.put(String.valueOf(7415), "Food and beverage tasters and graders");     
		occupations.put(String.valueOf(7416), "Tobacco preparers and tobacco products makers");     
		occupations.put(String.valueOf(7421), "Wood treaters");    
		occupations.put(String.valueOf(7422), "Cabinet makers and related workers");  
		occupations.put(String.valueOf(7423), "Woodworking machine setters and setter-operators");     
		occupations.put(String.valueOf(7424), "Basketry weavers, brush makers and related workers");      
		occupations.put(String.valueOf(7431), "Fibre preparers");   
		occupations.put(String.valueOf(7432), "Weavers, knitters and related workers");     
		occupations.put(String.valueOf(7433), "Tailors, dressmakers and hatters");     
		occupations.put(String.valueOf(7434), "Furriers and related workers");  
		occupations.put(String.valueOf(7435), "Textile, leather and related pattern-makers and cutters");        
		occupations.put(String.valueOf(7436), "Sewers, embroiderers and related workers");   
		occupations.put(String.valueOf(7437), "Upholsterers and related workers");  
		occupations.put(String.valueOf(7439), "Textile and dress-make workers");      
		occupations.put(String.valueOf(7441), "Pelt dressers, tanners and fellmongers");     
		occupations.put(String.valueOf(7442), "Shoe-makers and related workers");  
		occupations.put(String.valueOf(8111), "Mining-plant operators");     
		occupations.put(String.valueOf(8112), "Mineral-ore- and stone-processing-plant operators");       
		occupations.put(String.valueOf(8113), "Well drillers and borers and related workers");       
		occupations.put(String.valueOf(8121), "Ore and metal furnace operators");       
		occupations.put(String.valueOf(8122), "Metal melters, casters and rolling-mill operators");         
		occupations.put(String.valueOf(8123), "Metal-heat-treating-plant operators");      
		occupations.put(String.valueOf(8124), "Metal drawers and extruders");   
		occupations.put(String.valueOf(8131), "Glass and ceramics kiln and related machine operators");         
		occupations.put(String.valueOf(8132), "Glass, ceramics and related plant operators");        
		occupations.put(String.valueOf(8141), "Wood-processing-plant operators");      
		occupations.put(String.valueOf(8142), "Paper-pulp plant operators");     
		occupations.put(String.valueOf(8143), "Papermaking-plant operators");    
		occupations.put(String.valueOf(8151), "Crushing-, grinding- and chemical-mixing-machinery operators");      
		occupations.put(String.valueOf(8152), "Chemical-heat-treating-plant operators");      
		occupations.put(String.valueOf(8153), "Chemical-filtering- and separating-equipment operators");     
		occupations.put(String.valueOf(8154), "Chemical-still and reactor operators (except petroleum and natural gas)");       
		occupations.put(String.valueOf(8155), "Petroleum- and natural-gas-refining-plant operators");        
		occupations.put(String.valueOf(8159), "Chemical-processing-plant operators not elsewhere classified");      
		occupations.put(String.valueOf(8161), "Power-production plant operators");       
		occupations.put(String.valueOf(8162), "Steam-engine and boiler operators");        
		occupations.put(String.valueOf(8163), "Incinerator, water-treatment and related plant operators");        
		occupations.put(String.valueOf(8171), "Automated-assembly-line operators");        
		occupations.put(String.valueOf(8172), "Industrial-robot operators");        
		occupations.put(String.valueOf(8211), "Machine-tool operators");    
		occupations.put(String.valueOf(8212), "Cement and other mineral products machine operators");          
		occupations.put(String.valueOf(8221), "Pharmaceutical- and toiletry-products machine operators");        
		occupations.put(String.valueOf(8222), "Ammunition- and explosive-products machine operators");       
		occupations.put(String.valueOf(8223), "Metal finishing-, plating- and coating-machine operators");        
		occupations.put(String.valueOf(8224), "Photographic-products machine operators");      
		occupations.put(String.valueOf(8229), "Chemical-products machine operators not elsewhere classified");        
		occupations.put(String.valueOf(8231), "Rubber-products machine operators");     
		occupations.put(String.valueOf(8232), "Plastic-products machine operators");     
		occupations.put(String.valueOf(8241), "Wood-products machine operators");    
		occupations.put(String.valueOf(8251), "Printing-machine operators");    
		occupations.put(String.valueOf(8252), "Bookbinding-machine operators");     
		occupations.put(String.valueOf(8253), "Paper-products machine operators");      
		occupations.put(String.valueOf(8261), "Fibre-preparing-, spinning- and winding-machine operators");         
		occupations.put(String.valueOf(8262), "Weaving- and knitting-machine operators");     
		occupations.put(String.valueOf(8263), "Sewing-machine operators");     
		occupations.put(String.valueOf(8264), "Bleaching-, dyeing- and cleaning-machine operators");      
		occupations.put(String.valueOf(8265), "Fur- and leather-preparing-machine operators");      
		occupations.put(String.valueOf(8266), "Shoemaking- and related machine operators");      
		occupations.put(String.valueOf(8269), "Textile-, fur- and leather-products machine operators not elsewhere classified");      
		occupations.put(String.valueOf(8271), "Meat- and fish-processing-machine operators");      
		occupations.put(String.valueOf(8272), "Dairy-products machine operators");     
		occupations.put(String.valueOf(8273), "Grain- and spice-milling-machine operators");      
		occupations.put(String.valueOf(8274), "Baked-goods, cereal and chocolate-products machine operators");      
		occupations.put(String.valueOf(8275), "Fruit-, vegetable- and nut-processing-machine operators");       
		occupations.put(String.valueOf(8276), "Sugar production machine operators");     
		occupations.put(String.valueOf(8277), "Tea-, coffee-, and cocoa-processing-machine operators");         
		occupations.put(String.valueOf(8278), "Brewers, wine and other beverage machine operators");     
		occupations.put(String.valueOf(8279), "Tobacco production machine operators");     
		occupations.put(String.valueOf(8281), "Mechanical-machinery assemblers");    
		occupations.put(String.valueOf(8282), "Electrical-equipment assemblers");     
		occupations.put(String.valueOf(8283), "Electronic-equipment assemblers");     
		occupations.put(String.valueOf(8284), "Metal-, rubber- and plastic-products assemblers");      
		occupations.put(String.valueOf(8285), "Wood and related products assemblers");    
		occupations.put(String.valueOf(8286), "Paperboard, textile and related products assemblers");      
		occupations.put(String.valueOf(8290), "Other machine operators and assemblers");        
		occupations.put(String.valueOf(8311), "Locomotive-engine drivers");     
		occupations.put(String.valueOf(8312), "Railway brakers, signallers and shunters");   
		occupations.put(String.valueOf(8321), "Motor-cycle drivers");   
		occupations.put(String.valueOf(8322), "Car, taxi and van drivers");       
		occupations.put(String.valueOf(8323), "Bus and tram drivers");    
		occupations.put(String.valueOf(8324), "Heavy-truck and lorry drivers");    
		occupations.put(String.valueOf(8331), "Motorised farm and forestry plant operators");       
		occupations.put(String.valueOf(8332), "Earth-moving- and related plant operators");       
		occupations.put(String.valueOf(8333), "Crane, hoist and related plant operators");         
		occupations.put(String.valueOf(8334), "Lifting-truck operators");    
		occupations.put(String.valueOf(8340), "Ships' deck crews and related workers");         
		occupations.put(String.valueOf(9111), "Street food vendors");      
		occupations.put(String.valueOf(9112), "Street vendors, non-food products");      
		occupations.put(String.valueOf(9113), "Door-to-door and telephone salespersons");       
		occupations.put(String.valueOf(9121), "Shoe cleaning and other street services elementary occupations");        
		occupations.put(String.valueOf(9131), "Domestic helpers and cleaners");   
		occupations.put(String.valueOf(9132), "Helpers and cleaners in offices, hotels and other establishments");      
		occupations.put(String.valueOf(9133), "Hand-launderers and pressers");     
		occupations.put(String.valueOf(9141), "Building caretakers");   
		occupations.put(String.valueOf(9142), "Vehicle, window and related cleaners");      
		occupations.put(String.valueOf(9151), "Messengers, package and luggage porters and deliverers");        
		occupations.put(String.valueOf(9152), "Doorkeepers, watchpersons and related workers");     
		occupations.put(String.valueOf(9153), "Vending-machine money collectors, meter readers and related workers");        
		occupations.put(String.valueOf(9161), "Garbage collectors");   
		occupations.put(String.valueOf(9162), "Sweepers and related labourers");   
		occupations.put(String.valueOf(9211), "Farm-hands and labourers");   
		occupations.put(String.valueOf(9212), "Forestry labourers");  
		occupations.put(String.valueOf(9213), "Fishery, hunting and trapping labourers");       
		occupations.put(String.valueOf(9311), "Mining and quarrying labourers");   
		occupations.put(String.valueOf(9312), "Construction and maintenance labourers: roads, dams and similar constructions");       
		occupations.put(String.valueOf(9313), "Building construction labourers");   
		occupations.put(String.valueOf(9321), "Assembling labourers");  
		occupations.put(String.valueOf(9322), "Hand packers and other manufacturing labourers");      
		occupations.put(String.valueOf(9331), "Hand or pedal vehicle drivers");        
		occupations.put(String.valueOf(9332), "Drivers of animal-drawn vehicles and machinery");      
		occupations.put(String.valueOf(9333), "Freight handlers");   
	}
}

