package ae.payment.model.views;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Feb 21 20:01:13 GST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BrokenTransactionsViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public BrokenTransactionsViewImpl() {
    }

    /**
     * Returns the variable value for p_merchantId.
     * @return variable value for p_merchantId
     */
    public String getp_merchantId() {
        return (String)ensureVariableManager().getVariableValue("p_merchantId");
    }

    /**
     * Sets <code>value</code> for variable p_merchantId.
     * @param value value to bind as p_merchantId
     */
    public void setp_merchantId(String value) {
        ensureVariableManager().setVariableValue("p_merchantId", value);
    }

    /**
     * Returns the variable value for p_terminalNo.
     * @return variable value for p_terminalNo
     */
    public String getp_terminalNo() {
        return (String)ensureVariableManager().getVariableValue("p_terminalNo");
    }

    /**
     * Sets <code>value</code> for variable p_terminalNo.
     * @param value value to bind as p_terminalNo
     */
    public void setp_terminalNo(String value) {
        ensureVariableManager().setVariableValue("p_terminalNo", value);
    }

    /**
     * Returns the variable value for p_paymentId.
     * @return variable value for p_paymentId
     */
    public String getp_paymentId() {
        return (String)ensureVariableManager().getVariableValue("p_paymentId");
    }

    /**
     * Sets <code>value</code> for variable p_paymentId.
     * @param value value to bind as p_paymentId
     */
    public void setp_paymentId(String value) {
        ensureVariableManager().setVariableValue("p_paymentId", value);
    }
}
