package ae.payment.model.views;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Feb 22 14:50:00 GST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EServicesMatrixViewRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        DepartmentCode {
            public Object get(EServicesMatrixViewRowImpl obj) {
                return obj.getDepartmentCode();
            }

            public void put(EServicesMatrixViewRowImpl obj, Object value) {
                obj.setDepartmentCode((String)value);
            }
        }
        ,
        ServiceId {
            public Object get(EServicesMatrixViewRowImpl obj) {
                return obj.getServiceId();
            }

            public void put(EServicesMatrixViewRowImpl obj, Object value) {
                obj.setServiceId((String)value);
            }
        }
        ,
        Amount {
            public Object get(EServicesMatrixViewRowImpl obj) {
                return obj.getAmount();
            }

            public void put(EServicesMatrixViewRowImpl obj, Object value) {
                obj.setAmount((Number)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(EServicesMatrixViewRowImpl object);

        public abstract void put(EServicesMatrixViewRowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int DEPARTMENTCODE = AttributesEnum.DepartmentCode.index();
    public static final int SERVICEID = AttributesEnum.ServiceId.index();
    public static final int AMOUNT = AttributesEnum.Amount.index();

    /**
     * This is the default constructor (do not remove).
     */
    public EServicesMatrixViewRowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute DepartmentCode.
     * @return the DepartmentCode
     */
    public String getDepartmentCode() {
        return (String) getAttributeInternal(DEPARTMENTCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute DepartmentCode.
     * @param value value to set the  DepartmentCode
     */
    public void setDepartmentCode(String value) {
        setAttributeInternal(DEPARTMENTCODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ServiceId.
     * @return the ServiceId
     */
    public String getServiceId() {
        return (String) getAttributeInternal(SERVICEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ServiceId.
     * @param value value to set the  ServiceId
     */
    public void setServiceId(String value) {
        setAttributeInternal(SERVICEID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Amount.
     * @return the Amount
     */
    public Number getAmount() {
        return (Number) getAttributeInternal(AMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Amount.
     * @param value value to set the  Amount
     */
    public void setAmount(Number value) {
        setAttributeInternal(AMOUNT, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
