<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="XSD">
      <schema location="../xsd/GetAccountAttachments_table.xsd"/>
      <rootElement name="AccountattachmentsCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/GetAccountAttachments"/>
      <param name="accountattachmentsCollection" />
    </source>
    <source type="XSD">
      <schema location="../xsd/PaymentData.xsd"/>
      <rootElement name="Input" namespace="http://PaymentData"/>
      <param name="PaymentDataDetails" />
    </source>
  </mapSources>
  <mapTargets>
    <target type="XSD">
      <schema location="../xsd/PaymentData.xsd"/>
      <rootElement name="Input" namespace="http://PaymentData"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.8(build 150622.2350.0222) AT [WED JAN 27 19:58:38 GST 2016]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:pymnt="http://PaymentData"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:bpmn="http://schemas.oracle.com/bpm/xpath"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/top/GetAccountAttachments"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl pymnt xsd ns0 bpws xp20 mhdr bpel oraext dvm hwf med ids bpm xdk xref bpmn ora socket ldap">
  <xsl:param name="PaymentDataDetails"/>
  <xsl:template match="/">
    <pymnt:Input>
      <pymnt:UserDetails>
        <pymnt:Username>
          <xsl:value-of select="$PaymentDataDetails/pymnt:Input/pymnt:UserDetails/pymnt:Username"/>
        </pymnt:Username>
        <pymnt:TypeOfUser>
          <xsl:value-of select="$PaymentDataDetails/pymnt:Input/pymnt:UserDetails/pymnt:TypeOfUser"/>
        </pymnt:TypeOfUser>
        <xsl:if test="$PaymentDataDetails/pymnt:Input/pymnt:UserDetails/pymnt:Accountid">
          <pymnt:Accountid>
            <xsl:value-of select="$PaymentDataDetails/pymnt:Input/pymnt:UserDetails/pymnt:Accountid"/>
          </pymnt:Accountid>
        </xsl:if>
        <xsl:if test="$PaymentDataDetails/pymnt:Input/pymnt:UserDetails/pymnt:MobileNo">
          <pymnt:MobileNo>
            <xsl:value-of select="$PaymentDataDetails/pymnt:Input/pymnt:UserDetails/pymnt:MobileNo"/>
          </pymnt:MobileNo>
        </xsl:if>
        <xsl:if test="$PaymentDataDetails/pymnt:Input/pymnt:UserDetails/pymnt:EmailID">
          <pymnt:EmailID>
            <xsl:value-of select="$PaymentDataDetails/pymnt:Input/pymnt:UserDetails/pymnt:EmailID"/>
          </pymnt:EmailID>
        </xsl:if>
        <xsl:if test="$PaymentDataDetails/pymnt:Input/pymnt:UserDetails/pymnt:EmiratesId">
          <pymnt:EmiratesId>
            <xsl:value-of select="$PaymentDataDetails/pymnt:Input/pymnt:UserDetails/pymnt:EmiratesId"/>
          </pymnt:EmiratesId>
        </xsl:if>
        <xsl:if test="$PaymentDataDetails/pymnt:Input/pymnt:UserDetails/pymnt:TradeLienceNo">
          <pymnt:TradeLienceNo>
            <xsl:value-of select="$PaymentDataDetails/pymnt:Input/pymnt:UserDetails/pymnt:TradeLienceNo"/>
          </pymnt:TradeLienceNo>
        </xsl:if>
        <xsl:if test="$PaymentDataDetails/pymnt:Input/pymnt:UserDetails/pymnt:FamilyBookNo">
          <pymnt:FamilyBookNo>
            <xsl:value-of select="$PaymentDataDetails/pymnt:Input/pymnt:UserDetails/pymnt:FamilyBookNo"/>
          </pymnt:FamilyBookNo>
        </xsl:if>
        <pymnt:nationality>
          <xsl:value-of select="$PaymentDataDetails/pymnt:Input/pymnt:UserDetails/pymnt:nationality"/>
        </pymnt:nationality>
        <xsl:if test="$PaymentDataDetails/pymnt:Input/pymnt:UserDetails/pymnt:Emirate">
          <pymnt:Emirate>
            <xsl:value-of select="$PaymentDataDetails/pymnt:Input/pymnt:UserDetails/pymnt:Emirate"/>
          </pymnt:Emirate>
        </xsl:if>
        <xsl:if test="$PaymentDataDetails/pymnt:Input/pymnt:UserDetails/pymnt:FirstName">
          <pymnt:FirstName>
            <xsl:value-of select="$PaymentDataDetails/pymnt:Input/pymnt:UserDetails/pymnt:FirstName"/>
          </pymnt:FirstName>
        </xsl:if>
        <xsl:if test="$PaymentDataDetails/pymnt:Input/pymnt:UserDetails/pymnt:MiddleName">
          <pymnt:MiddleName>
            <xsl:value-of select="$PaymentDataDetails/pymnt:Input/pymnt:UserDetails/pymnt:MiddleName"/>
          </pymnt:MiddleName>
        </xsl:if>
        <xsl:if test="$PaymentDataDetails/pymnt:Input/pymnt:UserDetails/pymnt:LastName">
          <pymnt:LastName>
            <xsl:value-of select="$PaymentDataDetails/pymnt:Input/pymnt:UserDetails/pymnt:LastName"/>
          </pymnt:LastName>
        </xsl:if>
        <xsl:if test="$PaymentDataDetails/pymnt:Input/pymnt:UserDetails/pymnt:Address1">
          <pymnt:Address1>
            <xsl:value-of select="$PaymentDataDetails/pymnt:Input/pymnt:UserDetails/pymnt:Address1"/>
          </pymnt:Address1>
        </xsl:if>
        <xsl:if test="$PaymentDataDetails/pymnt:Input/pymnt:UserDetails/pymnt:Address2">
          <pymnt:Address2>
            <xsl:value-of select="$PaymentDataDetails/pymnt:Input/pymnt:UserDetails/pymnt:Address2"/>
          </pymnt:Address2>
        </xsl:if>
        <xsl:if test="$PaymentDataDetails/pymnt:Input/pymnt:UserDetails/pymnt:Address3">
          <pymnt:Address3>
            <xsl:value-of select="$PaymentDataDetails/pymnt:Input/pymnt:UserDetails/pymnt:Address3"/>
          </pymnt:Address3>
        </xsl:if>
        <xsl:if test="$PaymentDataDetails/pymnt:Input/pymnt:UserDetails/pymnt:POBOX">
          <pymnt:POBOX>
            <xsl:value-of select="$PaymentDataDetails/pymnt:Input/pymnt:UserDetails/pymnt:POBOX"/>
          </pymnt:POBOX>
        </xsl:if>
        <xsl:if test="$PaymentDataDetails/pymnt:Input/pymnt:UserDetails/pymnt:DOB">
          <pymnt:DOB>
            <xsl:value-of select="$PaymentDataDetails/pymnt:Input/pymnt:UserDetails/pymnt:DOB"/>
          </pymnt:DOB>
        </xsl:if>
        <xsl:if test="$PaymentDataDetails/pymnt:Input/pymnt:UserDetails/pymnt:applicanttypeid">
          <pymnt:applicanttypeid>
            <xsl:value-of select="$PaymentDataDetails/pymnt:Input/pymnt:UserDetails/pymnt:applicanttypeid"/>
          </pymnt:applicanttypeid>
        </xsl:if>
        <xsl:if test="$PaymentDataDetails/pymnt:Input/pymnt:UserDetails/pymnt:applicanttype_en">
          <pymnt:applicanttype_en>
            <xsl:value-of select="$PaymentDataDetails/pymnt:Input/pymnt:UserDetails/pymnt:applicanttype_en"/>
          </pymnt:applicanttype_en>
        </xsl:if>
        <xsl:if test="$PaymentDataDetails/pymnt:Input/pymnt:UserDetails/pymnt:applicanttype_ar">
          <pymnt:applicanttype_ar>
            <xsl:value-of select="$PaymentDataDetails/pymnt:Input/pymnt:UserDetails/pymnt:applicanttype_ar"/>
          </pymnt:applicanttype_ar>
        </xsl:if>
        <xsl:if test="$PaymentDataDetails/pymnt:Input/pymnt:UserDetails/pymnt:nationality_en">
          <pymnt:nationality_en>
            <xsl:value-of select="$PaymentDataDetails/pymnt:Input/pymnt:UserDetails/pymnt:nationality_en"/>
          </pymnt:nationality_en>
        </xsl:if>
        <xsl:if test="$PaymentDataDetails/pymnt:Input/pymnt:UserDetails/pymnt:nationality_ar">
          <pymnt:nationality_ar>
            <xsl:value-of select="$PaymentDataDetails/pymnt:Input/pymnt:UserDetails/pymnt:nationality_ar"/>
          </pymnt:nationality_ar>
        </xsl:if>
        <xsl:if test="$PaymentDataDetails/pymnt:Input/pymnt:UserDetails/pymnt:emirate_en">
          <pymnt:emirate_en>
            <xsl:value-of select="$PaymentDataDetails/pymnt:Input/pymnt:UserDetails/pymnt:emirate_en"/>
          </pymnt:emirate_en>
        </xsl:if>
        <xsl:if test="$PaymentDataDetails/pymnt:Input/pymnt:UserDetails/pymnt:emirate_ar">
          <pymnt:emirate_ar>
            <xsl:value-of select="$PaymentDataDetails/pymnt:Input/pymnt:UserDetails/pymnt:emirate_ar"/>
          </pymnt:emirate_ar>
        </xsl:if>
        <xsl:if test="$PaymentDataDetails/pymnt:Input/pymnt:UserDetails/pymnt:typeofuser_en">
          <pymnt:typeofuser_en>
            <xsl:value-of select="$PaymentDataDetails/pymnt:Input/pymnt:UserDetails/pymnt:typeofuser_en"/>
          </pymnt:typeofuser_en>
        </xsl:if>
        <xsl:if test="$PaymentDataDetails/pymnt:Input/pymnt:UserDetails/pymnt:typeofuser_ar">
          <pymnt:typeofuser_ar>
            <xsl:value-of select="$PaymentDataDetails/pymnt:Input/pymnt:UserDetails/pymnt:typeofuser_ar"/>
          </pymnt:typeofuser_ar>
        </xsl:if>
      </pymnt:UserDetails>
      <pymnt:RequestDetails>
        <xsl:if test="$PaymentDataDetails/pymnt:Input/pymnt:RequestDetails/pymnt:ServiceId">
          <pymnt:ServiceId>
            <xsl:value-of select="$PaymentDataDetails/pymnt:Input/pymnt:RequestDetails/pymnt:ServiceId"/>
          </pymnt:ServiceId>
        </xsl:if>
        <xsl:if test="$PaymentDataDetails/pymnt:Input/pymnt:RequestDetails/pymnt:ServiceName">
          <pymnt:ServiceName>
            <xsl:value-of select="$PaymentDataDetails/pymnt:Input/pymnt:RequestDetails/pymnt:ServiceName"/>
          </pymnt:ServiceName>
        </xsl:if>
        <xsl:if test="$PaymentDataDetails/pymnt:Input/pymnt:RequestDetails/pymnt:RequestType">
          <pymnt:RequestType>
            <xsl:value-of select="$PaymentDataDetails/pymnt:Input/pymnt:RequestDetails/pymnt:RequestType"/>
          </pymnt:RequestType>
        </xsl:if>
        <pymnt:RequestDate>
          <xsl:value-of select="xp20:current-date()"/>
        </pymnt:RequestDate>
        <xsl:if test="$PaymentDataDetails/pymnt:Input/pymnt:RequestDetails/pymnt:FeeTypeCode">
          <pymnt:FeeTypeCode>
            <xsl:value-of select="$PaymentDataDetails/pymnt:Input/pymnt:RequestDetails/pymnt:FeeTypeCode"/>
          </pymnt:FeeTypeCode>
        </xsl:if>
        <xsl:if test="$PaymentDataDetails/pymnt:Input/pymnt:RequestDetails/pymnt:UserType">
          <pymnt:UserType>
            <xsl:value-of select="$PaymentDataDetails/pymnt:Input/pymnt:RequestDetails/pymnt:UserType"/>
          </pymnt:UserType>
        </xsl:if>
        <xsl:if test="$PaymentDataDetails/pymnt:Input/pymnt:RequestDetails/pymnt:Letter">
          <pymnt:Letter>
            <xsl:if test="$PaymentDataDetails/pymnt:Input/pymnt:RequestDetails/pymnt:Letter/@xsi:nil">
              <xsl:attribute name="xsi:nil">
                <xsl:value-of select="$PaymentDataDetails/pymnt:Input/pymnt:RequestDetails/pymnt:Letter/@xsi:nil"/>
              </xsl:attribute>
            </xsl:if>
            <xsl:value-of select="$PaymentDataDetails/pymnt:Input/pymnt:RequestDetails/pymnt:Letter"/>
          </pymnt:Letter>
        </xsl:if>
        <xsl:if test="$PaymentDataDetails/pymnt:Input/pymnt:RequestDetails/pymnt:RequestNumber">
          <pymnt:RequestNumber>
            <xsl:value-of select="$PaymentDataDetails/pymnt:Input/pymnt:RequestDetails/pymnt:RequestNumber"/>
          </pymnt:RequestNumber>
        </xsl:if>
        <xsl:if test="$PaymentDataDetails/pymnt:Input/pymnt:RequestDetails/pymnt:RequestStatus">
          <pymnt:RequestStatus>
            <xsl:value-of select="$PaymentDataDetails/pymnt:Input/pymnt:RequestDetails/pymnt:RequestStatus"/>
          </pymnt:RequestStatus>
        </xsl:if>
        <pymnt:cashierGrpName>
          <xsl:text disable-output-escaping="no"></xsl:text>
        </pymnt:cashierGrpName>
      </pymnt:RequestDetails>
      <pymnt:PaymentDetails>
        <pymnt:TotalAmount>
          <xsl:text disable-output-escaping="no"></xsl:text>
        </pymnt:TotalAmount>
        <pymnt:GeneralAmount>
          <xsl:text disable-output-escaping="no"></xsl:text>
        </pymnt:GeneralAmount>
        <xsl:choose>
          <xsl:when test='string-length($PaymentDataDetails/pymnt:Input/pymnt:PaymentDetails/pymnt:ApplicationAmount) != "0"'>
            <pymnt:ApplicationAmount>
              <xsl:value-of select="$PaymentDataDetails/pymnt:Input/pymnt:PaymentDetails/pymnt:ApplicationAmount"/>
            </pymnt:ApplicationAmount>
          </xsl:when>
          <xsl:otherwise>
            <pymnt:ApplicationAmount>
              <xsl:text disable-output-escaping="no"></xsl:text>
            </pymnt:ApplicationAmount>
          </xsl:otherwise>
        </xsl:choose>
        <xsl:choose>
          <xsl:when test='string-length($PaymentDataDetails/pymnt:Input/pymnt:PaymentDetails/pymnt:ServiceAmount) != "0"'>
            <pymnt:ServiceAmount>
              <xsl:value-of select="$PaymentDataDetails/pymnt:Input/pymnt:PaymentDetails/pymnt:ServiceAmount"/>
            </pymnt:ServiceAmount>
          </xsl:when>
          <xsl:otherwise>
            <pymnt:ServiceAmount>
              <xsl:text disable-output-escaping="no"></xsl:text>
            </pymnt:ServiceAmount>
          </xsl:otherwise>
        </xsl:choose>
        <xsl:choose>
          <xsl:when test='string-length($PaymentDataDetails/pymnt:Input/pymnt:PaymentDetails/pymnt:specificDeptCode) != "0"'>
            <pymnt:specificDeptCode>
              <xsl:value-of select="$PaymentDataDetails/pymnt:Input/pymnt:PaymentDetails/pymnt:specificDeptCode"/>
            </pymnt:specificDeptCode>
          </xsl:when>
          <xsl:otherwise>
            <pymnt:specificDeptCode>
              <xsl:text disable-output-escaping="no"></xsl:text>
            </pymnt:specificDeptCode>
          </xsl:otherwise>
        </xsl:choose>
        <pymnt:GeneralDeptCode>
          <xsl:text disable-output-escaping="no"></xsl:text>
        </pymnt:GeneralDeptCode>
        <xsl:choose>
          <xsl:when test='string-length($PaymentDataDetails/pymnt:Input/pymnt:PaymentDetails/pymnt:SpecificFeeId) != "0"'>
            <pymnt:SpecificFeeId>
              <xsl:value-of select="$PaymentDataDetails/pymnt:Input/pymnt:PaymentDetails/pymnt:SpecificFeeId"/>
            </pymnt:SpecificFeeId>
          </xsl:when>
          <xsl:otherwise>
            <pymnt:SpecificFeeId>
              <xsl:text disable-output-escaping="no"></xsl:text>
            </pymnt:SpecificFeeId>
          </xsl:otherwise>
        </xsl:choose>
        <pymnt:GeneralFeeId>
          <xsl:text disable-output-escaping="no"></xsl:text>
        </pymnt:GeneralFeeId>
        <pymnt:PaymentMethod>
          <xsl:text disable-output-escaping="no"></xsl:text>
        </pymnt:PaymentMethod>
        <xsl:if test="$PaymentDataDetails/pymnt:Input/pymnt:PaymentDetails/pymnt:DepartmentName">
          <pymnt:DepartmentName>
            <xsl:value-of select="$PaymentDataDetails/pymnt:Input/pymnt:PaymentDetails/pymnt:DepartmentName"/>
          </pymnt:DepartmentName>
        </xsl:if>
        <pymnt:ReceiptNumber>
          <xsl:text disable-output-escaping="no"></xsl:text>
        </pymnt:ReceiptNumber>
        <pymnt:Imagelogopath>
          <xsl:text disable-output-escaping="no"></xsl:text>
        </pymnt:Imagelogopath>
      </pymnt:PaymentDetails>
      <pymnt:POSDetails>
        <pymnt:Amount>
          <xsl:text disable-output-escaping="no"></xsl:text>
        </pymnt:Amount>
        <pymnt:EcrIdNo>
          <xsl:text disable-output-escaping="no"></xsl:text>
        </pymnt:EcrIdNo>
        <xsl:if test="$PaymentDataDetails/pymnt:Input/pymnt:POSDetails/pymnt:ServiceCode">
          <pymnt:ServiceCode>
            <xsl:value-of select="$PaymentDataDetails/pymnt:Input/pymnt:POSDetails/pymnt:ServiceCode"/>
          </pymnt:ServiceCode>
        </xsl:if>
        <xsl:if test="$PaymentDataDetails/pymnt:Input/pymnt:POSDetails/pymnt:TransactionType">
          <pymnt:TransactionType>
            <xsl:value-of select="$PaymentDataDetails/pymnt:Input/pymnt:POSDetails/pymnt:TransactionType"/>
          </pymnt:TransactionType>
        </xsl:if>
        <xsl:if test="$PaymentDataDetails/pymnt:Input/pymnt:POSDetails/pymnt:TerminalNo">
          <pymnt:TerminalNo>
            <xsl:value-of select="$PaymentDataDetails/pymnt:Input/pymnt:POSDetails/pymnt:TerminalNo"/>
          </pymnt:TerminalNo>
        </xsl:if>
        <xsl:if test="$PaymentDataDetails/pymnt:Input/pymnt:POSDetails/pymnt:MerchantId">
          <pymnt:MerchantId>
            <xsl:value-of select="$PaymentDataDetails/pymnt:Input/pymnt:POSDetails/pymnt:MerchantId"/>
          </pymnt:MerchantId>
        </xsl:if>
        <pymnt:PaymentId>
          <xsl:text disable-output-escaping="no"></xsl:text>
        </pymnt:PaymentId>
        <pymnt:FeeId>
          <xsl:text disable-output-escaping="no"></xsl:text>
        </pymnt:FeeId>
        <pymnt:CustomerId>
          <xsl:text disable-output-escaping="no"></xsl:text>
        </pymnt:CustomerId>
        <pymnt:CustomerName>
          <xsl:text disable-output-escaping="no"></xsl:text>
        </pymnt:CustomerName>
      </pymnt:POSDetails>
      <pymnt:AccountIdentityAttachmentList>
        <xsl:for-each select="/ns0:AccountattachmentsCollection/ns0:Accountattachments">
          <pymnt:accountAttachmentRec>
            <xsl:if test="ns0:contentid">
              <pymnt:contentid>
                <xsl:value-of select="ns0:contentid"/>
              </pymnt:contentid>
            </xsl:if>
            <pymnt:doctypeid>
              <xsl:value-of select="ns0:attachementtype"/>
            </pymnt:doctypeid>
            <xsl:choose>
              <xsl:when test='ns0:attachementtype = "1"'>
                <pymnt:doctype_en>
                  <xsl:text disable-output-escaping="no">Trade License Number</xsl:text>
                </pymnt:doctype_en>
              </xsl:when>
              <xsl:when test='ns0:attachementtype = "2"'>
                <pymnt:doctype_en>
                  <xsl:text disable-output-escaping="no">Signatory Attestation</xsl:text>
                </pymnt:doctype_en>
              </xsl:when>
              <xsl:when test='ns0:attachementtype = "3"'>
                <pymnt:doctype_en>
                  <xsl:text disable-output-escaping="no">Chamber Of Commerce</xsl:text>
                </pymnt:doctype_en>
              </xsl:when>
              <xsl:when test='ns0:attachementtype = "4"'>
                <pymnt:doctype_en>
                  <xsl:text disable-output-escaping="no">Certificate</xsl:text>
                </pymnt:doctype_en>
              </xsl:when>
              <xsl:when test='ns0:attachementtype = "5"'>
                <pymnt:doctype_en>
                  <xsl:text disable-output-escaping="no">Taken Picture</xsl:text>
                </pymnt:doctype_en>
              </xsl:when>
              <xsl:when test='ns0:attachementtype = "8"'>
                <pymnt:doctype_en>
                  <xsl:text disable-output-escaping="no">Passport</xsl:text>
                </pymnt:doctype_en>
              </xsl:when>
              <xsl:when test='ns0:attachementtype = "9"'>
                <pymnt:doctype_en>
                  <xsl:text disable-output-escaping="no">EmiratesID</xsl:text>
                </pymnt:doctype_en>
              </xsl:when>
              <xsl:when test='ns0:attachementtype = "16"'>
                <pymnt:doctype_en>
                  <xsl:text disable-output-escaping="no">Identity of the PRO</xsl:text>
                </pymnt:doctype_en>
              </xsl:when>
              <xsl:when test='ns0:attachementtype = "17"'>
                <pymnt:doctype_en>
                  <xsl:text disable-output-escaping="no">PRO Photograph</xsl:text>
                </pymnt:doctype_en>
              </xsl:when>
              <xsl:when test='ns0:attachementtype = "18"'>
                <pymnt:doctype_en>
                  <xsl:text disable-output-escaping="no">PRO Delegation</xsl:text>
                </pymnt:doctype_en>
              </xsl:when>
              <xsl:when test='ns0:attachementtype = "19"'>
                <pymnt:doctype_en>
                  <xsl:text disable-output-escaping="no">Real Estate Trading License</xsl:text>
                </pymnt:doctype_en>
              </xsl:when>
              <xsl:when test='ns0:attachementtype = "20"'>
                <pymnt:doctype_en>
                  <xsl:text disable-output-escaping="no">Family Book</xsl:text>
                </pymnt:doctype_en>
              </xsl:when>
              <xsl:when test='ns0:attachementtype = "21"'>
                <pymnt:doctype_en>
                  <xsl:text disable-output-escaping="no">Spouse Emirates ID</xsl:text>
                </pymnt:doctype_en>
              </xsl:when>
              <xsl:when test='ns0:attachementtype = "22"'>
                <pymnt:doctype_en>
                  <xsl:text disable-output-escaping="no">Emirate Id Front</xsl:text>
                </pymnt:doctype_en>
              </xsl:when>
              <xsl:when test='ns0:attachementtype = "23"'>
                <pymnt:doctype_en>
                  <xsl:text disable-output-escaping="no">Emirate Id Back</xsl:text>
                </pymnt:doctype_en>
              </xsl:when>
              <xsl:when test='ns0:attachementtype = "24"'>
                <pymnt:doctype_en>
                  <xsl:text disable-output-escaping="no">Passport Front</xsl:text>
                </pymnt:doctype_en>
              </xsl:when>
              <xsl:when test='ns0:attachementtype = "25"'>
                <pymnt:doctype_en>
                  <xsl:text disable-output-escaping="no">Passport Residency Page</xsl:text>
                </pymnt:doctype_en>
              </xsl:when>
              <xsl:when test='ns0:attachementtype = "26"'>
                <pymnt:doctype_en>
                  <xsl:text disable-output-escaping="no">Visa Page</xsl:text>
                </pymnt:doctype_en>
              </xsl:when>
              <xsl:otherwise>
                <pymnt:doctype_en>
                  <xsl:text disable-output-escaping="no">Generic Document</xsl:text>
                </pymnt:doctype_en>
              </xsl:otherwise>
            </xsl:choose>
            <xsl:if test="ns0:url">
              <pymnt:viewurl>
                <xsl:value-of select="ns0:url"/>
              </pymnt:viewurl>
            </xsl:if>
            <xsl:if test="ns0:url">
              <pymnt:downloadurl>
                <xsl:value-of select="ns0:url"/>
              </pymnt:downloadurl>
            </xsl:if>
            <pymnt:filename>
              <xsl:value-of select="ns0:attachemntname"/>
            </pymnt:filename>
          </pymnt:accountAttachmentRec>
        </xsl:for-each>
      </pymnt:AccountIdentityAttachmentList>
    </pymnt:Input>
  </xsl:template>
</xsl:stylesheet>
