<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="XSD">
      <schema location="../xsd/GetLookUpsFrmDB.xsd"/>
      <rootElement name="GetLookUpsFrmDBOutputCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/GetLookUpsFrmDB"/>
      <param name="lookUpsFrmDBOutputCollection" />
    </source>
    <source type="XSD">
      <schema location="../xsd/PaymentData.xsd"/>
      <rootElement name="Input" namespace="http://PaymentData"/>
      <param name="PaymentDataDetails" />
    </source>
  </mapSources>
  <mapTargets>
    <target type="XSD">
      <schema location="../xsd/PaymentData.xsd"/>
      <rootElement name="Input" namespace="http://PaymentData"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 150407.0554.0203) AT [SUN DEC 27 00:38:59 GST 2015]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/GetLookUpsFrmDB"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:pymnt="http://PaymentData"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:bpmn="http://schemas.oracle.com/bpm/xpath"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl ns0 pymnt xsd bpws xp20 mhdr bpel oraext dvm hwf med ids bpm xdk xref bpmn ora socket ldap">
  <xsl:param name="PaymentDataDetails"/>
  <xsl:template match="/">
    <pymnt:Input>
      <pymnt:UserDetails>
        <pymnt:Username>
          <xsl:value-of select="$PaymentDataDetails/pymnt:Input/pymnt:UserDetails/pymnt:Username"/>
        </pymnt:Username>
        <pymnt:TypeOfUser>
          <xsl:value-of select="$PaymentDataDetails/pymnt:Input/pymnt:UserDetails/pymnt:TypeOfUser"/>
        </pymnt:TypeOfUser>
        <xsl:if test="$PaymentDataDetails/pymnt:Input/pymnt:UserDetails/pymnt:Accountid">
          <pymnt:Accountid>
            <xsl:value-of select="$PaymentDataDetails/pymnt:Input/pymnt:UserDetails/pymnt:Accountid"/>
          </pymnt:Accountid>
        </xsl:if>
        <xsl:if test="$PaymentDataDetails/pymnt:Input/pymnt:UserDetails/pymnt:MobileNo">
          <pymnt:MobileNo>
            <xsl:value-of select="$PaymentDataDetails/pymnt:Input/pymnt:UserDetails/pymnt:MobileNo"/>
          </pymnt:MobileNo>
        </xsl:if>
        <xsl:if test="$PaymentDataDetails/pymnt:Input/pymnt:UserDetails/pymnt:EmailID">
          <pymnt:EmailID>
            <xsl:value-of select="$PaymentDataDetails/pymnt:Input/pymnt:UserDetails/pymnt:EmailID"/>
          </pymnt:EmailID>
        </xsl:if>
        <xsl:if test="$PaymentDataDetails/pymnt:Input/pymnt:UserDetails/pymnt:EmiratesId">
          <pymnt:EmiratesId>
            <xsl:value-of select="$PaymentDataDetails/pymnt:Input/pymnt:UserDetails/pymnt:EmiratesId"/>
          </pymnt:EmiratesId>
        </xsl:if>
        <xsl:if test="$PaymentDataDetails/pymnt:Input/pymnt:UserDetails/pymnt:TradeLienceNo">
          <pymnt:TradeLienceNo>
            <xsl:value-of select="$PaymentDataDetails/pymnt:Input/pymnt:UserDetails/pymnt:TradeLienceNo"/>
          </pymnt:TradeLienceNo>
        </xsl:if>
        <xsl:if test="$PaymentDataDetails/pymnt:Input/pymnt:UserDetails/pymnt:FamilyBookNo">
          <pymnt:FamilyBookNo>
            <xsl:value-of select="$PaymentDataDetails/pymnt:Input/pymnt:UserDetails/pymnt:FamilyBookNo"/>
          </pymnt:FamilyBookNo>
        </xsl:if>
        <pymnt:nationality>
          <xsl:value-of select="$PaymentDataDetails/pymnt:Input/pymnt:UserDetails/pymnt:nationality"/>
        </pymnt:nationality>
        <xsl:if test="$PaymentDataDetails/pymnt:Input/pymnt:UserDetails/pymnt:Emirate">
          <pymnt:Emirate>
            <xsl:value-of select="$PaymentDataDetails/pymnt:Input/pymnt:UserDetails/pymnt:Emirate"/>
          </pymnt:Emirate>
        </xsl:if>
        <xsl:if test="$PaymentDataDetails/pymnt:Input/pymnt:UserDetails/pymnt:FirstName">
          <pymnt:FirstName>
            <xsl:value-of select="$PaymentDataDetails/pymnt:Input/pymnt:UserDetails/pymnt:FirstName"/>
          </pymnt:FirstName>
        </xsl:if>
        <xsl:if test="$PaymentDataDetails/pymnt:Input/pymnt:UserDetails/pymnt:MiddleName">
          <pymnt:MiddleName>
            <xsl:value-of select="$PaymentDataDetails/pymnt:Input/pymnt:UserDetails/pymnt:MiddleName"/>
          </pymnt:MiddleName>
        </xsl:if>
        <xsl:if test="$PaymentDataDetails/pymnt:Input/pymnt:UserDetails/pymnt:LastName">
          <pymnt:LastName>
            <xsl:value-of select="$PaymentDataDetails/pymnt:Input/pymnt:UserDetails/pymnt:LastName"/>
          </pymnt:LastName>
        </xsl:if>
        <xsl:if test="$PaymentDataDetails/pymnt:Input/pymnt:UserDetails/pymnt:Address1">
          <pymnt:Address1>
            <xsl:value-of select="$PaymentDataDetails/pymnt:Input/pymnt:UserDetails/pymnt:Address1"/>
          </pymnt:Address1>
        </xsl:if>
        <xsl:if test="$PaymentDataDetails/pymnt:Input/pymnt:UserDetails/pymnt:Address2">
          <pymnt:Address2>
            <xsl:value-of select="$PaymentDataDetails/pymnt:Input/pymnt:UserDetails/pymnt:Address2"/>
          </pymnt:Address2>
        </xsl:if>
        <xsl:if test="$PaymentDataDetails/pymnt:Input/pymnt:UserDetails/pymnt:Address3">
          <pymnt:Address3>
            <xsl:value-of select="$PaymentDataDetails/pymnt:Input/pymnt:UserDetails/pymnt:Address3"/>
          </pymnt:Address3>
        </xsl:if>
        <xsl:if test="$PaymentDataDetails/pymnt:Input/pymnt:UserDetails/pymnt:POBOX">
          <pymnt:POBOX>
            <xsl:value-of select="$PaymentDataDetails/pymnt:Input/pymnt:UserDetails/pymnt:POBOX"/>
          </pymnt:POBOX>
        </xsl:if>
        <xsl:if test="$PaymentDataDetails/pymnt:Input/pymnt:UserDetails/pymnt:DOB">
          <pymnt:DOB>
            <xsl:value-of select="$PaymentDataDetails/pymnt:Input/pymnt:UserDetails/pymnt:DOB"/>
          </pymnt:DOB>
        </xsl:if>
        <xsl:if test="$PaymentDataDetails/pymnt:Input/pymnt:UserDetails/pymnt:applicanttypeid">
          <pymnt:applicanttypeid>
            <xsl:value-of select="$PaymentDataDetails/pymnt:Input/pymnt:UserDetails/pymnt:applicanttypeid"/>
          </pymnt:applicanttypeid>
        </xsl:if>
        <pymnt:applicanttype_en>
          <xsl:value-of select="/ns0:GetLookUpsFrmDBOutputCollection/ns0:GetLookUpsFrmDBOutput/ns0:apptypeEngname"/>
        </pymnt:applicanttype_en>
        <pymnt:applicanttype_ar>
          <xsl:value-of select="/ns0:GetLookUpsFrmDBOutputCollection/ns0:GetLookUpsFrmDBOutput/ns0:apptypeArbname"/>
        </pymnt:applicanttype_ar>
        <pymnt:nationality_en>
          <xsl:value-of select="/ns0:GetLookUpsFrmDBOutputCollection/ns0:GetLookUpsFrmDBOutput/ns0:usernatEng"/>
        </pymnt:nationality_en>
        <pymnt:nationality_ar>
          <xsl:value-of select="/ns0:GetLookUpsFrmDBOutputCollection/ns0:GetLookUpsFrmDBOutput/ns0:usernatArb"/>
        </pymnt:nationality_ar>
        <pymnt:emirate_en>
          <xsl:value-of select="/ns0:GetLookUpsFrmDBOutputCollection/ns0:GetLookUpsFrmDBOutput/ns0:emirateEng"/>
        </pymnt:emirate_en>
        <pymnt:emirate_ar>
          <xsl:value-of select="/ns0:GetLookUpsFrmDBOutputCollection/ns0:GetLookUpsFrmDBOutput/ns0:emirateArb"/>
        </pymnt:emirate_ar>
        <pymnt:typeofuser_en>
          <xsl:value-of select="/ns0:GetLookUpsFrmDBOutputCollection/ns0:GetLookUpsFrmDBOutput/ns0:typeofuserEngName"/>
        </pymnt:typeofuser_en>
        <pymnt:typeofuser_ar>
          <xsl:value-of select="/ns0:GetLookUpsFrmDBOutputCollection/ns0:GetLookUpsFrmDBOutput/ns0:typeofuserArabicname"/>
        </pymnt:typeofuser_ar>
      </pymnt:UserDetails>
      <pymnt:RequestDetails>
        <xsl:if test="$PaymentDataDetails/pymnt:Input/pymnt:RequestDetails/pymnt:ServiceId">
          <pymnt:ServiceId>
            <xsl:value-of select="$PaymentDataDetails/pymnt:Input/pymnt:RequestDetails/pymnt:ServiceId"/>
          </pymnt:ServiceId>
        </xsl:if>
        <xsl:if test="$PaymentDataDetails/pymnt:Input/pymnt:RequestDetails/pymnt:ServiceName">
          <pymnt:ServiceName>
            <xsl:value-of select="$PaymentDataDetails/pymnt:Input/pymnt:RequestDetails/pymnt:ServiceName"/>
          </pymnt:ServiceName>
        </xsl:if>
        <xsl:if test="$PaymentDataDetails/pymnt:Input/pymnt:RequestDetails/pymnt:RequestType">
          <pymnt:RequestType>
            <xsl:value-of select="$PaymentDataDetails/pymnt:Input/pymnt:RequestDetails/pymnt:RequestType"/>
          </pymnt:RequestType>
        </xsl:if>
        <xsl:if test="$PaymentDataDetails/pymnt:Input/pymnt:RequestDetails/pymnt:RequestDate">
          <pymnt:RequestDate>
            <xsl:value-of select="$PaymentDataDetails/pymnt:Input/pymnt:RequestDetails/pymnt:RequestDate"/>
          </pymnt:RequestDate>
        </xsl:if>
        <xsl:if test="$PaymentDataDetails/pymnt:Input/pymnt:RequestDetails/pymnt:FeeTypeCode">
          <pymnt:FeeTypeCode>
            <xsl:value-of select="$PaymentDataDetails/pymnt:Input/pymnt:RequestDetails/pymnt:FeeTypeCode"/>
          </pymnt:FeeTypeCode>
        </xsl:if>
        <xsl:if test="$PaymentDataDetails/pymnt:Input/pymnt:RequestDetails/pymnt:UserType">
          <pymnt:UserType>
            <xsl:value-of select="$PaymentDataDetails/pymnt:Input/pymnt:RequestDetails/pymnt:UserType"/>
          </pymnt:UserType>
        </xsl:if>
        <xsl:if test="$PaymentDataDetails/pymnt:Input/pymnt:RequestDetails/pymnt:Letter">
          <pymnt:Letter>
            <xsl:if test="$PaymentDataDetails/pymnt:Input/pymnt:RequestDetails/pymnt:Letter/@xsi:nil">
              <xsl:attribute name="xsi:nil">
                <xsl:value-of select="$PaymentDataDetails/pymnt:Input/pymnt:RequestDetails/pymnt:Letter/@xsi:nil"/>
              </xsl:attribute>
            </xsl:if>
            <xsl:value-of select="$PaymentDataDetails/pymnt:Input/pymnt:RequestDetails/pymnt:Letter"/>
          </pymnt:Letter>
        </xsl:if>
        <xsl:if test="$PaymentDataDetails/pymnt:Input/pymnt:RequestDetails/pymnt:RequestNumber">
          <pymnt:RequestNumber>
            <xsl:value-of select="$PaymentDataDetails/pymnt:Input/pymnt:RequestDetails/pymnt:RequestNumber"/>
          </pymnt:RequestNumber>
        </xsl:if>
        <xsl:if test="$PaymentDataDetails/pymnt:Input/pymnt:RequestDetails/pymnt:RequestStatus">
          <pymnt:RequestStatus>
            <xsl:value-of select="$PaymentDataDetails/pymnt:Input/pymnt:RequestDetails/pymnt:RequestStatus"/>
          </pymnt:RequestStatus>
        </xsl:if>
      </pymnt:RequestDetails>
      <pymnt:PaymentDetails>
        <xsl:if test="$PaymentDataDetails/pymnt:Input/pymnt:PaymentDetails/pymnt:TotalAmount">
          <pymnt:TotalAmount>
            <xsl:value-of select="$PaymentDataDetails/pymnt:Input/pymnt:PaymentDetails/pymnt:TotalAmount"/>
          </pymnt:TotalAmount>
        </xsl:if>
        <xsl:if test="$PaymentDataDetails/pymnt:Input/pymnt:PaymentDetails/pymnt:GeneralAmount">
          <pymnt:GeneralAmount>
            <xsl:value-of select="$PaymentDataDetails/pymnt:Input/pymnt:PaymentDetails/pymnt:GeneralAmount"/>
          </pymnt:GeneralAmount>
        </xsl:if>
        <xsl:if test="$PaymentDataDetails/pymnt:Input/pymnt:PaymentDetails/pymnt:ApplicationAmount">
          <pymnt:ApplicationAmount>
            <xsl:value-of select="$PaymentDataDetails/pymnt:Input/pymnt:PaymentDetails/pymnt:ApplicationAmount"/>
          </pymnt:ApplicationAmount>
        </xsl:if>
        <xsl:if test="$PaymentDataDetails/pymnt:Input/pymnt:PaymentDetails/pymnt:ServiceAmount">
          <pymnt:ServiceAmount>
            <xsl:value-of select="$PaymentDataDetails/pymnt:Input/pymnt:PaymentDetails/pymnt:ServiceAmount"/>
          </pymnt:ServiceAmount>
        </xsl:if>
        <xsl:if test="$PaymentDataDetails/pymnt:Input/pymnt:PaymentDetails/pymnt:specificDeptCode">
          <pymnt:specificDeptCode>
            <xsl:value-of select="$PaymentDataDetails/pymnt:Input/pymnt:PaymentDetails/pymnt:specificDeptCode"/>
          </pymnt:specificDeptCode>
        </xsl:if>
        <xsl:if test="$PaymentDataDetails/pymnt:Input/pymnt:PaymentDetails/pymnt:GeneralDeptCode">
          <pymnt:GeneralDeptCode>
            <xsl:value-of select="$PaymentDataDetails/pymnt:Input/pymnt:PaymentDetails/pymnt:GeneralDeptCode"/>
          </pymnt:GeneralDeptCode>
        </xsl:if>
        <xsl:if test="$PaymentDataDetails/pymnt:Input/pymnt:PaymentDetails/pymnt:SpecificFeeId">
          <pymnt:SpecificFeeId>
            <xsl:value-of select="$PaymentDataDetails/pymnt:Input/pymnt:PaymentDetails/pymnt:SpecificFeeId"/>
          </pymnt:SpecificFeeId>
        </xsl:if>
        <xsl:if test="$PaymentDataDetails/pymnt:Input/pymnt:PaymentDetails/pymnt:GeneralFeeId">
          <pymnt:GeneralFeeId>
            <xsl:value-of select="$PaymentDataDetails/pymnt:Input/pymnt:PaymentDetails/pymnt:GeneralFeeId"/>
          </pymnt:GeneralFeeId>
        </xsl:if>
        <xsl:if test="$PaymentDataDetails/pymnt:Input/pymnt:PaymentDetails/pymnt:PaymentMethod">
          <pymnt:PaymentMethod>
            <xsl:value-of select="$PaymentDataDetails/pymnt:Input/pymnt:PaymentDetails/pymnt:PaymentMethod"/>
          </pymnt:PaymentMethod>
        </xsl:if>
        <xsl:if test="$PaymentDataDetails/pymnt:Input/pymnt:PaymentDetails/pymnt:DepartmentName">
          <pymnt:DepartmentName>
            <xsl:value-of select="$PaymentDataDetails/pymnt:Input/pymnt:PaymentDetails/pymnt:DepartmentName"/>
          </pymnt:DepartmentName>
        </xsl:if>
      </pymnt:PaymentDetails>
      <pymnt:POSDetails>
        <xsl:if test="$PaymentDataDetails/pymnt:Input/pymnt:POSDetails/pymnt:Amount">
          <pymnt:Amount>
            <xsl:value-of select="$PaymentDataDetails/pymnt:Input/pymnt:POSDetails/pymnt:Amount"/>
          </pymnt:Amount>
        </xsl:if>
        <xsl:if test="$PaymentDataDetails/pymnt:Input/pymnt:POSDetails/pymnt:EcrIdNo">
          <pymnt:EcrIdNo>
            <xsl:value-of select="$PaymentDataDetails/pymnt:Input/pymnt:POSDetails/pymnt:EcrIdNo"/>
          </pymnt:EcrIdNo>
        </xsl:if>
        <xsl:if test="$PaymentDataDetails/pymnt:Input/pymnt:POSDetails/pymnt:ServiceCode">
          <pymnt:ServiceCode>
            <xsl:value-of select="$PaymentDataDetails/pymnt:Input/pymnt:POSDetails/pymnt:ServiceCode"/>
          </pymnt:ServiceCode>
        </xsl:if>
        <xsl:if test="$PaymentDataDetails/pymnt:Input/pymnt:POSDetails/pymnt:TransactionType">
          <pymnt:TransactionType>
            <xsl:value-of select="$PaymentDataDetails/pymnt:Input/pymnt:POSDetails/pymnt:TransactionType"/>
          </pymnt:TransactionType>
        </xsl:if>
        <xsl:if test="$PaymentDataDetails/pymnt:Input/pymnt:POSDetails/pymnt:TerminalNo">
          <pymnt:TerminalNo>
            <xsl:value-of select="$PaymentDataDetails/pymnt:Input/pymnt:POSDetails/pymnt:TerminalNo"/>
          </pymnt:TerminalNo>
        </xsl:if>
        <xsl:if test="$PaymentDataDetails/pymnt:Input/pymnt:POSDetails/pymnt:MerchantId">
          <pymnt:MerchantId>
            <xsl:value-of select="$PaymentDataDetails/pymnt:Input/pymnt:POSDetails/pymnt:MerchantId"/>
          </pymnt:MerchantId>
        </xsl:if>
        <xsl:if test="$PaymentDataDetails/pymnt:Input/pymnt:POSDetails/pymnt:PaymentId">
          <pymnt:PaymentId>
            <xsl:value-of select="$PaymentDataDetails/pymnt:Input/pymnt:POSDetails/pymnt:PaymentId"/>
          </pymnt:PaymentId>
        </xsl:if>
        <xsl:if test="$PaymentDataDetails/pymnt:Input/pymnt:POSDetails/pymnt:FeeId">
          <pymnt:FeeId>
            <xsl:value-of select="$PaymentDataDetails/pymnt:Input/pymnt:POSDetails/pymnt:FeeId"/>
          </pymnt:FeeId>
        </xsl:if>
        <xsl:if test="$PaymentDataDetails/pymnt:Input/pymnt:POSDetails/pymnt:CustomerId">
          <pymnt:CustomerId>
            <xsl:value-of select="$PaymentDataDetails/pymnt:Input/pymnt:POSDetails/pymnt:CustomerId"/>
          </pymnt:CustomerId>
        </xsl:if>
        <xsl:if test="$PaymentDataDetails/pymnt:Input/pymnt:POSDetails/pymnt:CustomerName">
          <pymnt:CustomerName>
            <xsl:value-of select="$PaymentDataDetails/pymnt:Input/pymnt:POSDetails/pymnt:CustomerName"/>
          </pymnt:CustomerName>
        </xsl:if>
      </pymnt:POSDetails>
      <pymnt:AccountIdentityAttachmentList>
        <xsl:for-each select="$PaymentDataDetails/pymnt:Input/pymnt:AccountIdentityAttachmentList/pymnt:accountAttachmentRec">
          <pymnt:accountAttachmentRec>
            <xsl:if test="pymnt:contentid">
              <pymnt:contentid>
                <xsl:value-of select="pymnt:contentid"/>
              </pymnt:contentid>
            </xsl:if>
            <xsl:if test="pymnt:doctypeid">
              <pymnt:doctypeid>
                <xsl:value-of select="pymnt:doctypeid"/>
              </pymnt:doctypeid>
            </xsl:if>
            <xsl:if test="pymnt:doctype_en">
              <pymnt:doctype_en>
                <xsl:value-of select="pymnt:doctype_en"/>
              </pymnt:doctype_en>
            </xsl:if>
            <xsl:if test="pymnt:doctype_ar">
              <pymnt:doctype_ar>
                <xsl:value-of select="pymnt:doctype_ar"/>
              </pymnt:doctype_ar>
            </xsl:if>
            <xsl:if test="pymnt:viewurl">
              <pymnt:viewurl>
                <xsl:value-of select="pymnt:viewurl"/>
              </pymnt:viewurl>
            </xsl:if>
            <xsl:if test="pymnt:downloadurl">
              <pymnt:downloadurl>
                <xsl:value-of select="pymnt:downloadurl"/>
              </pymnt:downloadurl>
            </xsl:if>
            <xsl:if test="pymnt:filename">
              <pymnt:filename>
                <xsl:value-of select="pymnt:filename"/>
              </pymnt:filename>
            </xsl:if>
          </pymnt:accountAttachmentRec>
        </xsl:for-each>
      </pymnt:AccountIdentityAttachmentList>
    </pymnt:Input>
  </xsl:template>
</xsl:stylesheet>
