<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="XSD">
      <schema location="../xsd/PaymentData.xsd"/>
      <rootElement name="Input" namespace="http://PaymentData"/>
      <param name="PaymentDataDetails" />
    </source>
  </mapSources>
  <mapTargets>
    <target type="XSD">
      <schema location="../xsd/ERP_Finance_table.xsd"/>
      <rootElement name="XxUaqEserviceIntegTblCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/ERP_Finance"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 150407.0554.0203) AT [THU JAN 21 18:12:24 GST 2016]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:pymnt="http://PaymentData"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/top/ERP_Finance"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:bpmn="http://schemas.oracle.com/bpm/xpath"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl pymnt xsd ns0 bpws xp20 mhdr bpel oraext dvm hwf med ids bpm xdk xref bpmn ora socket ldap">
  <xsl:template match="/">
    <ns0:XxUaqEserviceIntegTblCollection>
      <ns0:XxUaqEserviceIntegTbl>
        <ns0:currencyCode>
          <xsl:text disable-output-escaping="no">AED</xsl:text>
        </ns0:currencyCode>
        <xsl:choose>
          <xsl:when test='/pymnt:Input/pymnt:RequestDetails/pymnt:FeeTypeCode = "A001"'>
            <ns0:amount>
              <xsl:value-of select="/pymnt:Input/pymnt:PaymentDetails/pymnt:ApplicationAmount"/>
            </ns0:amount>
          </xsl:when>
          <xsl:when test='/pymnt:Input/pymnt:RequestDetails/pymnt:FeeTypeCode = "S001"'>
            <ns0:amount>
              <xsl:value-of select="/pymnt:Input/pymnt:PaymentDetails/pymnt:ServiceAmount"/>
            </ns0:amount>
          </xsl:when>
        </xsl:choose>
        <ns0:departmentCode>
          <xsl:value-of select="/pymnt:Input/pymnt:PaymentDetails/pymnt:specificDeptCode"/>
        </ns0:departmentCode>
        <ns0:receiptMethodType>
          <xsl:value-of select="/pymnt:Input/pymnt:PaymentDetails/pymnt:PaymentMethod"/>
        </ns0:receiptMethodType>
        <ns0:feesId>
          <xsl:value-of select="/pymnt:Input/pymnt:PaymentDetails/pymnt:SpecificFeeId"/>
        </ns0:feesId>
        <ns0:customerId>
          <xsl:value-of select="/pymnt:Input/pymnt:UserDetails/pymnt:Accountid"/>
        </ns0:customerId>
        <ns0:customerName>
          <xsl:value-of select="/pymnt:Input/pymnt:UserDetails/pymnt:FirstName"/>
        </ns0:customerName>
        <ns0:transactionDate>
          <xsl:value-of select="xp20:current-date()"/>
        </ns0:transactionDate>
      </ns0:XxUaqEserviceIntegTbl>
    </ns0:XxUaqEserviceIntegTblCollection>
  </xsl:template>
</xsl:stylesheet>
